//
// UserPickerUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A user found in a search. */

public struct UserPickerUser {

    /** The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. */
    public var accountId: String?
    /** The avatar URL of the user. */
    public var avatarUrl: String?
    /** The display name of the user. Depending on the user’s privacy setting, this may be returned as null. */
    public var displayName: String?
    /** The display name, email address, and key of the user with the matched query string highlighted with the HTML bold tag. */
    public var html: String?
    /** This property is no longer available. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    public var key: String?
    /** This property is no longer available . See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    public var name: String?

    public init(accountId: String? = nil, avatarUrl: String? = nil, displayName: String? = nil, html: String? = nil, key: String? = nil, name: String? = nil) {
        self.accountId = accountId
        self.avatarUrl = avatarUrl
        self.displayName = displayName
        self.html = html
        self.key = key
        self.name = name
    }


}
