//
// IssueLink.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a link between issues. */

public struct IssueLink {

    /** The ID of the issue link. */
    public let id: String?
    /** Provides details about the linked issue. If presenting this link in a user interface, use the &#x60;inward&#x60; field of the issue link type to label the link. */
    public let inwardIssue: LinkedIssue
    /** Provides details about the linked issue. If presenting this link in a user interface, use the &#x60;outward&#x60; field of the issue link type to label the link. */
    public let outwardIssue: LinkedIssue
    /** The URL of the issue link. */
    public let _self: String?
    /** The type of link between the issues. */
    public let type: IssueLinkType

    public init(
        id: String? = nil,
        inwardIssue: LinkedIssue,
        outwardIssue: LinkedIssue,
        _self: String? = nil,
        type: IssueLinkType
    ) {
        self.id = id
        self.inwardIssue = inwardIssue
        self.outwardIssue = outwardIssue
        self._self = _self
        self.type = type
    }
    
    internal init(client: Components.Schemas.IssueLink?) {
        self.id = client?.id
        self.inwardIssue = client?.inwardIssue.
    }

}
