//
// IssueList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of issue IDs. */

public struct IssueList {

    /** The list of issue IDs. */
    public var issueIds: [String]

    public init(issueIds: [String]) {
        self.issueIds = issueIds
    }


}
