//
// LinkedIssue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The ID or key of a linked issue. */

public struct LinkedIssue {

    /** The fields associated with the issue. */
    public var fields: Fields?
    /** The ID of an issue. Required if &#x60;key&#x60; isn&#x27;t provided. */
    public var id: String?
    /** The key of an issue. Required if &#x60;id&#x60; isn&#x27;t provided. */
    public var key: String?
    /** The URL of the issue. */
    public var _self: String?

    public init(fields: Fields? = nil, id: String? = nil, key: String? = nil, _self: String? = nil) {
        self.fields = fields
        self.id = id
        self.key = key
        self._self = _self
    }

    public enum CodingKeys: String, CodingKey {
        case _self = "self"
    }
    
    internal init(client: Components.Schemas.LinkedIssue?) {
        self.fields = Fields(client: client?.fields?.value1)
        self.id = client?.id
        self.key = client?.key
        self._self = client?._self
    }
}
