//
// CreatedIssues.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the issues created and the errors for requests that failed. */

public struct CreatedIssues {

    /** Error details for failed issue creation requests. */
    public var errors: [BulkOperationErrorResult]?
    /** Details of the issues created. */
    public var issues: [CreatedIssue]?

    public init(errors: [BulkOperationErrorResult]? = nil, issues: [CreatedIssue]? = nil) {
        self.errors = errors
        self.issues = issues
    }


}
