//
// IssuesMetaBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Meta data describing the &#x60;issues&#x60; context variable. */

public struct IssuesMetaBean {

    public var jql: IssuesJqlMetaDataBean?

    public init(jql: IssuesJqlMetaDataBean? = nil) {
        self.jql = jql
    }


}
