//
// IssuePickerSuggestionsIssueType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A type of issue suggested for use in auto-completion. */

public struct IssuePickerSuggestionsIssueType {

    /** The ID of the type of issues suggested for use in auto-completion. */
    public var _id: String?
    /** A list of issues suggested for use in auto-completion. */
    public var issues: [SuggestedIssue]?
    /** The label of the type of issues suggested for use in auto-completion. */
    public var label: String?
    /** If no issue suggestions are found, returns a message indicating no suggestions were found, */
    public var msg: String?
    /** If issue suggestions are found, returns a message indicating the number of issues suggestions found and returned. */
    public var sub: String?

    public init(_id: String? = nil, issues: [SuggestedIssue]? = nil, label: String? = nil, msg: String? = nil, sub: String? = nil) {
        self._id = _id
        self.issues = issues
        self.label = label
        self.msg = msg
        self.sub = sub
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case issues
        case label
        case msg
        case sub
    }

}
