//
// WorkflowSchemeProjectAssociation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An associated workflow scheme and project. */

public struct WorkflowSchemeProjectAssociation: Codable {

    /** The ID of the project. */
    public var projectId: String
    /** The ID of the workflow scheme. If the workflow scheme ID is &#x60;null&#x60;, the operation assigns the default workflow scheme. */
    public var workflowSchemeId: String?

    public init(projectId: String, workflowSchemeId: String? = nil) {
        self.projectId = projectId
        self.workflowSchemeId = workflowSchemeId
    }


}
