//
// WorkflowUpdateValidateRequestBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WorkflowUpdateValidateRequestBean {

    public var payload: WorkflowUpdateRequest
    public var validationOptions: ValidationOptionsForUpdate?

    public init(payload: WorkflowUpdateRequest, validationOptions: ValidationOptionsForUpdate? = nil) {
        self.payload = payload
        self.validationOptions = validationOptions
    }


}
