//
// WorkflowSchemeUpdateRequiredMappingsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The request payload to get the required mappings for updating a workflow scheme. */

public struct WorkflowSchemeUpdateRequiredMappingsRequest: Codable {

    /** The ID of the new default workflow for this workflow scheme. Only used in global-scoped workflow schemes. If it isn&#x27;t specified, is set to *Jira Workflow (jira)*. */
    public var defaultWorkflowId: String?
    /** The ID of the workflow scheme. */
    public var _id: String
    /** The new workflow to issue type mappings for this workflow scheme. */
    public var workflowsForIssueTypes: [WorkflowSchemeAssociation]

    public init(defaultWorkflowId: String? = nil, _id: String, workflowsForIssueTypes: [WorkflowSchemeAssociation]) {
        self.defaultWorkflowId = defaultWorkflowId
        self._id = _id
        self.workflowsForIssueTypes = workflowsForIssueTypes
    }

    public enum CodingKeys: String, CodingKey { 
        case defaultWorkflowId
        case _id = "id"
        case workflowsForIssueTypes
    }

}
