//
// WorkflowSchemeAssociation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The explicit association between issue types and a workflow in a workflow scheme. */

public struct WorkflowSchemeAssociation {

    /** The issue types assigned to the workflow. */
    public var issueTypeIds: [String]
    /** The ID of the workflow. */
    public var workflowId: String

    public init(issueTypeIds: [String], workflowId: String) {
        self.issueTypeIds = issueTypeIds
        self.workflowId = workflowId
    }


}
