//
// WorkflowValidationError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The details about a workflow validation error. */

public struct WorkflowValidationError: Codable {

    public enum Level: String, Codable { 
        case warning = "WARNING"
        case error = "ERROR"
    }
    public enum ModelType: String, Codable { 
        case rule = "RULE"
        case status = "STATUS"
        case statusLayout = "STATUS_LAYOUT"
        case statusProperty = "STATUS_PROPERTY"
        case workflow = "WORKFLOW"
        case transition = "TRANSITION"
        case transitionProperty = "TRANSITION_PROPERTY"
        case scope = "SCOPE"
        case statusMapping = "STATUS_MAPPING"
        case trigger = "TRIGGER"
    }
    /** An error code. */
    public var code: String?
    public var elementReference: WorkflowElementReference?
    /** The validation error level. */
    public var level: Level?
    /** An error message. */
    public var message: String?
    /** The type of element the error or warning references. */
    public var type: ModelType?

    public init(code: String? = nil, elementReference: WorkflowElementReference? = nil, level: Level? = nil, message: String? = nil, type: ModelType? = nil) {
        self.code = code
        self.elementReference = elementReference
        self.level = level
        self.message = message
        self.type = type
    }


}
