//
// WorkflowStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a workflow status. */

public struct WorkflowStatus: Codable {

    /** The ID of the issue status. */
    public var _id: String
    /** The name of the status in the workflow. */
    public var name: String
    /** Additional properties that modify the behavior of issues in this status. Supports the properties &#x60;jira.issue.editable&#x60; and &#x60;issueEditable&#x60; (deprecated) that indicate whether issues are editable. */
    public var properties: [String:Any]?

    public init(_id: String, name: String, properties: [String:Any]? = nil) {
        self._id = _id
        self.name = name
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case properties
    }

}
