//
// WorkflowUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The update workflows payload. */

public struct WorkflowUpdateRequest {

    /** The statuses to associate with the workflows. */
    public var statuses: [WorkflowStatusUpdate]
    /** The details of the workflows to update. */
    public var workflows: [WorkflowUpdate]

    public init(statuses: [WorkflowStatusUpdate], workflows: [WorkflowUpdate]) {
        self.statuses = statuses
        self.workflows = workflows
    }


}
