//
// WorkflowReadResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of workflows and related statuses. */

public struct WorkflowReadResponse: Codable {

    /** List of statuses. */
    public var statuses: [JiraWorkflowStatus]?
    /** List of workflows. */
    public var workflows: [JiraWorkflow]?

    public init(statuses: [JiraWorkflowStatus]? = nil, workflows: [JiraWorkflow]? = nil) {
        self.statuses = statuses
        self.workflows = workflows
    }


}
