//
// WorkflowElementReference.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A reference to the location of the error. This will be null if the error does not refer to a specific element. */

public struct WorkflowElementReference: Codable {

    /** A property key. */
    public var propertyKey: String?
    /** A rule ID. */
    public var ruleId: String?
    public var statusMappingReference: ProjectAndIssueTypePair?
    /** A status reference. */
    public var statusReference: String?
    /** A transition ID. */
    public var transitionId: String?

    public init(propertyKey: String? = nil, ruleId: String? = nil, statusMappingReference: ProjectAndIssueTypePair? = nil, statusReference: String? = nil, transitionId: String? = nil) {
        self.propertyKey = propertyKey
        self.ruleId = ruleId
        self.statusMappingReference = statusMappingReference
        self.statusReference = statusReference
        self.transitionId = transitionId
    }


}
