//
// AllOfFieldsStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The status of the linked issue. */

public struct AllOfFieldsStatus {

    /** The description of the status. */
    public var _description: String?
    /** The URL of the icon used to represent the status. */
    public var iconUrl: String?
    /** The ID of the status. */
    public var _id: String?
    /** The name of the status. */
    public var name: String?
    /** The scope of the field. */
    public var scope: Any?
    /** The URL of the status. */
    public var _self: String?
    /** The category assigned to the status. */
    public var statusCategory: Any?

    public init(_description: String? = nil, iconUrl: String? = nil, _id: String? = nil, name: String? = nil, scope: Any? = nil, _self: String? = nil, statusCategory: Any? = nil) {
        self._description = _description
        self.iconUrl = iconUrl
        self._id = _id
        self.name = name
        self.scope = scope
        self._self = _self
        self.statusCategory = statusCategory
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case iconUrl
        case _id = "id"
        case name
        case scope
        case _self = "self"
        case statusCategory
    }

}
