//
// AllOfFieldsIssueType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The type of the linked issue. */

public struct AllOfFieldsIssueType {

    /** The ID of the issue type&#x27;s avatar. */
    public var avatarId: Int64?
    /** The description of the issue type. */
    public var _description: String?
    /** Unique ID for next-gen projects. */
    public var entityId: UUID?
    /** Hierarchy level of the issue type. */
    public var hierarchyLevel: Int?
    /** The URL of the issue type&#x27;s avatar. */
    public var iconUrl: String?
    /** The ID of the issue type. */
    public var _id: String?
    /** The name of the issue type. */
    public var name: String?
    /** Details of the next-gen projects the issue type is available in. */
    public var scope: Any?
    /** The URL of these issue type details. */
    public var _self: String?
    /** Whether this issue type is used to create subtasks. */
    public var subtask: Bool?
    /** Untranslated name of the issue from original creator */
    public var untranslatedName: String?

    public init(avatarId: Int64? = nil, _description: String? = nil, entityId: UUID? = nil, hierarchyLevel: Int? = nil, iconUrl: String? = nil, _id: String? = nil, name: String? = nil, scope: Any? = nil, _self: String? = nil, subtask: Bool? = nil, untranslatedName: String? = nil) {
        self.avatarId = avatarId
        self._description = _description
        self.entityId = entityId
        self.hierarchyLevel = hierarchyLevel
        self.iconUrl = iconUrl
        self._id = _id
        self.name = name
        self.scope = scope
        self._self = _self
        self.subtask = subtask
        self.untranslatedName = untranslatedName
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarId
        case _description = "description"
        case entityId
        case hierarchyLevel
        case iconUrl
        case _id = "id"
        case name
        case scope
        case _self = "self"
        case subtask
        case untranslatedName
    }

}
