//
// Fields.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Key fields from the linked issue. */

public struct Fields {

    /** The assignee of the linked issue. */
    public var assignee: User?
    /** The type of the linked issue. */
    public var issueType: IssueTypeDetails?
    /** The priority of the linked issue. */
    public var priority: Priority?
    /** The status of the linked issue. */
    public var status: Status?
    /** The summary description of the linked issue. */
    public var summary: String?
    /** The time tracking of the linked issue. */
    public var timetracking: TimeTrackingDetails?

    public init(
        assignee: User? = nil,
        issueType: IssueTypeDetails? = nil,
        priority: Priority? = nil,
        status: Status? = nil,
        summary: String? = nil,
        timetracking: TimeTrackingDetails? = nil
    ) {
        self.assignee = assignee
        self.issueType = issueType
        self.priority = priority
        self.status = status
        self.summary = summary
        self.timetracking = timetracking
    }

    internal init(client: Components.Schemas.Fields?) {
        self.assignee = User(client: client?.assignee?.value1)
        self.issueType = IssueTypeDetails(client: client?.issueType?.value1)
        self.priority = Priority(client: client?.priority?.value1)
        self.status = Status(client: client?.status?.value1)
        self.summary = client?.summary
        self.timetracking = TimeTrackingDetails(
            client: client?.timetracking?.value1
        )
    }

}
