//
// AddFieldBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AddFieldBean: Codable {

    /** The ID of the field to add. */
    public var fieldId: String

    public init(fieldId: String) {
        self.fieldId = fieldId
    }


}
