//
// AllOfJiraExpressionEvaluationMetaDataBeanIssues.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information about the &#x60;issues&#x60; variable in the context. For example, is the issues were loaded with JQL, information about the page will be included here. */

public struct AllOfJiraExpressionEvaluationMetaDataBeanIssues: Codable {

    public var jql: IssuesJqlMetaDataBean?

    public init(jql: IssuesJqlMetaDataBean? = nil) {
        self.jql = jql
    }


}
