//
// AllOfProjectWithDataPolicyDataPolicy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Data policy. */

public struct AllOfProjectWithDataPolicyDataPolicy {

    /** Whether the project contains any content inaccessible to the requesting application. */
    public var anyContentBlocked: Bool?

    public init(anyContentBlocked: Bool? = nil) {
        self.anyContentBlocked = anyContentBlocked
    }


}
