//
// AllOfVersionIssuesStatusForFixVersion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** If the expand option &#x60;issuesstatus&#x60; is used, returns the count of issues in this version for each of the status categories *to do*, *in progress*, *done*, and *unmapped*. The *unmapped* property contains a count of issues with a status other than *to do*, *in progress*, and *done*. */

public struct AllOfVersionIssuesStatusForFixVersion: Codable {

    /** Count of issues with status *done*. */
    public var done: Int64?
    /** Count of issues with status *in progress*. */
    public var inProgress: Int64?
    /** Count of issues with status *to do*. */
    public var toDo: Int64?
    /** Count of issues with a status other than *to do*, *in progress*, and *done*. */
    public var unmapped: Int64?

    public init(done: Int64? = nil, inProgress: Int64? = nil, toDo: Int64? = nil, unmapped: Int64? = nil) {
        self.done = done
        self.inProgress = inProgress
        self.toDo = toDo
        self.unmapped = unmapped
    }


}
