//
// AnnouncementBannerConfiguration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Announcement banner configuration. */

public struct AnnouncementBannerConfiguration: Codable {

    public enum Visibility: String, Codable { 
        case _public = "PUBLIC"
        case _private = "PRIVATE"
    }
    /** Hash of the banner data. The client detects updates by comparing hash IDs. */
    public var hashId: String?
    /** Flag indicating if the announcement banner can be dismissed by the user. */
    public var isDismissible: Bool?
    /** Flag indicating if the announcement banner is enabled or not. */
    public var isEnabled: Bool?
    /** The text on the announcement banner. */
    public var message: String?
    /** Visibility of the announcement banner. */
    public var visibility: Visibility?

    public init(hashId: String? = nil, isDismissible: Bool? = nil, isEnabled: Bool? = nil, message: String? = nil, visibility: Visibility? = nil) {
        self.hashId = hashId
        self.isDismissible = isDismissible
        self.isEnabled = isEnabled
        self.message = message
        self.visibility = visibility
    }


}
