//
// AttachmentArchiveEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AttachmentArchiveEntry: Codable {

    public var abbreviatedName: String?
    public var entryIndex: Int64?
    public var mediaType: String?
    public var name: String?
    public var size: Int64?

    public init(abbreviatedName: String? = nil, entryIndex: Int64? = nil, mediaType: String? = nil, name: String? = nil, size: Int64? = nil) {
        self.abbreviatedName = abbreviatedName
        self.entryIndex = entryIndex
        self.mediaType = mediaType
        self.name = name
        self.size = size
    }


}
