//
// AttachmentSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the instance&#x27;s attachment settings. */

public struct AttachmentSettings: Codable {

    /** Whether the ability to add attachments is enabled. */
    public var enabled: Bool?
    /** The maximum size of attachments permitted, in bytes. */
    public var uploadLimit: Int64?

    public init(enabled: Bool? = nil, uploadLimit: Int64? = nil) {
        self.enabled = enabled
        self.uploadLimit = uploadLimit
    }


}
