//
// AttachmentArchiveImpl.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AttachmentArchiveImpl: Codable {

    /** The list of the items included in the archive. */
    public var entries: [AttachmentArchiveEntry]?
    /** The number of items in the archive. */
    public var totalEntryCount: Int?

    public init(entries: [AttachmentArchiveEntry]? = nil, totalEntryCount: Int? = nil) {
        self.entries = entries
        self.totalEntryCount = totalEntryCount
    }


}
