//
// AttachmentArchiveMetadataReadable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Metadata for an archive (for example a zip) and its contents. */

public struct AttachmentArchiveMetadataReadable: Codable {

    /** The list of the items included in the archive. */
    public var entries: [AttachmentArchiveItemReadable]?
    /** The ID of the attachment. */
    public var _id: Int64?
    /** The MIME type of the attachment. */
    public var mediaType: String?
    /** The name of the archive file. */
    public var name: String?
    /** The number of items included in the archive. */
    public var totalEntryCount: Int64?

    public init(entries: [AttachmentArchiveItemReadable]? = nil, _id: Int64? = nil, mediaType: String? = nil, name: String? = nil, totalEntryCount: Int64? = nil) {
        self.entries = entries
        self._id = _id
        self.mediaType = mediaType
        self.name = name
        self.totalEntryCount = totalEntryCount
    }

    public enum CodingKeys: String, CodingKey { 
        case entries
        case _id = "id"
        case mediaType
        case name
        case totalEntryCount
    }

}
