//
// AutoCompleteSuggestion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A field auto-complete suggestion. */

public struct AutoCompleteSuggestion: Codable {

    /** The display name of a suggested item. If &#x60;fieldValue&#x60; or &#x60;predicateValue&#x60; are provided, the matching text is highlighted with the HTML bold tag. */
    public var displayName: String?
    /** The value of a suggested item. */
    public var value: String?

    public init(displayName: String? = nil, value: String? = nil) {
        self.displayName = displayName
        self.value = value
    }


}
