//
// AvailableDashboardGadgetsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of available gadgets. */

public struct AvailableDashboardGadgetsResponse {

    /** The list of available gadgets. */
    public var gadgets: [AvailableDashboardGadget]

    public init(gadgets: [AvailableDashboardGadget]) {
        self.gadgets = gadgets
    }


}
