//
// AvailableWorkflowConnectRule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Connect provided ecosystem rules available. */

public struct AvailableWorkflowConnectRule: Codable {

    public enum RuleType: String, Codable { 
        case condition = "Condition"
        case validator = "Validator"
        case function = "Function"
        case screen = "Screen"
    }
    /** The add-on providing the rule. */
    public var addonKey: String?
    /** The URL creation path segment defined in the Connect module. */
    public var createUrl: String?
    /** The rule description. */
    public var _description: String?
    /** The URL edit path segment defined in the Connect module. */
    public var editUrl: String?
    /** The module providing the rule. */
    public var moduleKey: String?
    /** The rule name. */
    public var name: String?
    /** The rule key. */
    public var ruleKey: String?
    /** The rule type. */
    public var ruleType: RuleType?
    /** The URL view path segment defined in the Connect module. */
    public var viewUrl: String?

    public init(addonKey: String? = nil, createUrl: String? = nil, _description: String? = nil, editUrl: String? = nil, moduleKey: String? = nil, name: String? = nil, ruleKey: String? = nil, ruleType: RuleType? = nil, viewUrl: String? = nil) {
        self.addonKey = addonKey
        self.createUrl = createUrl
        self._description = _description
        self.editUrl = editUrl
        self.moduleKey = moduleKey
        self.name = name
        self.ruleKey = ruleKey
        self.ruleType = ruleType
        self.viewUrl = viewUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case addonKey
        case createUrl
        case _description = "description"
        case editUrl
        case moduleKey
        case name
        case ruleKey
        case ruleType
        case viewUrl
    }

}
