//
// BulkChangeOwnerDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details for changing owners of shareable entities */

public struct BulkChangeOwnerDetails: Codable {

    /** Whether the name is fixed automatically if it&#x27;s duplicated after changing owner. */
    public var autofixName: Bool
    /** The account id of the new owner. */
    public var newOwner: String

    public init(autofixName: Bool, newOwner: String) {
        self.autofixName = autofixName
        self.newOwner = newOwner
    }


}
