//
// BulkEditShareableEntityRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a request to bulk edit shareable entity. */

public struct BulkEditShareableEntityRequest: Codable {

    public enum Action: String, Codable { 
        case changeowner = "changeOwner"
        case changepermission = "changePermission"
        case addpermission = "addPermission"
        case removepermission = "removePermission"
    }
    /** Allowed action for bulk edit shareable entity */
    public var action: Action
    /** The details of change owner action. */
    public var changeOwnerDetails: AllOfBulkEditShareableEntityRequestChangeOwnerDetails?
    /** The id list of shareable entities to be changed. */
    public var entityIds: [Int64]
    /** Whether the actions are executed by users with Administer Jira global permission. */
    public var extendAdminPermissions: Bool?
    /** The permission details to be changed. */
    public var permissionDetails: AllOfBulkEditShareableEntityRequestPermissionDetails?

    public init(action: Action, changeOwnerDetails: AllOfBulkEditShareableEntityRequestChangeOwnerDetails? = nil, entityIds: [Int64], extendAdminPermissions: Bool? = nil, permissionDetails: AllOfBulkEditShareableEntityRequestPermissionDetails? = nil) {
        self.action = action
        self.changeOwnerDetails = changeOwnerDetails
        self.entityIds = entityIds
        self.extendAdminPermissions = extendAdminPermissions
        self.permissionDetails = permissionDetails
    }


}
