//
// BulkIssuePropertyUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Bulk issue property update request details. */

public struct BulkIssuePropertyUpdateRequest: Codable {

    /** EXPERIMENTAL. The Jira expression to calculate the value of the property. The value of the expression must be an object that can be converted to JSON, such as a number, boolean, string, list, or map. The context variables available to the expression are &#x60;issue&#x60; and &#x60;user&#x60;. Issues for which the expression returns a value whose JSON representation is longer than 32768 characters are ignored. */
    public var expression: String?
    /** The bulk operation filter. */
    public var filter: AllOfBulkIssuePropertyUpdateRequestFilter?
    /** The value of the property. The value must be a [valid](https://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters. */
    public var value: Any?

    public init(expression: String? = nil, filter: AllOfBulkIssuePropertyUpdateRequestFilter? = nil, value: Any? = nil) {
        self.expression = expression
        self.filter = filter
        self.value = value
    }


}
