//
// ChangeFilterOwner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The account ID of the new owner. */

public struct ChangeFilterOwner: Codable {

    /** The account ID of the new owner. */
    public var accountId: String

    public init(accountId: String) {
        self.accountId = accountId
    }


}
