//
// ColumnItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of an issue navigator column item. */

public struct ColumnItem: Codable {

    /** The issue navigator column label. */
    public var label: String?
    /** The issue navigator column value. */
    public var value: String?

    public init(label: String? = nil, value: String? = nil) {
        self.label = label
        self.value = value
    }


}
