//
// ConditionGroupUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The conditions group associated with the transition. */

public struct ConditionGroupUpdate: Codable {

    public enum Operation: String, Codable { 
        case any = "ANY"
        case all = "ALL"
    }
    /** The nested conditions of the condition group. */
    public var conditionGroups: [ConditionGroupUpdate]?
    /** The rules for this condition. */
    public var conditions: [WorkflowRuleConfiguration]?
    /** Determines how the conditions in the group are evaluated. Accepts either &#x60;ANY&#x60; or &#x60;ALL&#x60;. If &#x60;ANY&#x60; is used, at least one condition in the group must be true for the group to evaluate to true. If &#x60;ALL&#x60; is used, all conditions in the group must be true for the group to evaluate to true. */
    public var operation: Operation

    public init(conditionGroups: [ConditionGroupUpdate]? = nil, conditions: [WorkflowRuleConfiguration]? = nil, operation: Operation) {
        self.conditionGroups = conditionGroups
        self.conditions = conditions
        self.operation = operation
    }


}
