//
// Context.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A context. */

public struct Context: Codable {

    /** The ID of the context. */
    public var _id: Int64?
    /** The name of the context. */
    public var name: String?
    /** The scope of the context. */
    public var scope: AllOfContextScope?

    public init(_id: Int64? = nil, name: String? = nil, scope: AllOfContextScope? = nil) {
        self._id = _id
        self.name = name
        self.scope = scope
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case scope
    }

}
