//
// ContainerForProjectFeatures.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of features on a project. */

public struct ContainerForProjectFeatures: Codable {

    /** The project features. */
    public var features: [ProjectFeature]?

    public init(features: [ProjectFeature]? = nil) {
        self.features = features
    }


}
