//
// CreateResolutionDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of an issue resolution. */

public struct CreateResolutionDetails: Codable {




}
