//
// CreatedIssue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a created issue or subtask. */

public struct CreatedIssue {

    /** The ID of the created issue or subtask. */
    public var _id: String?
    /** The key of the created issue or subtask. */
    public var key: String?
    /** The URL of the created issue or subtask. */
    public var _self: String?
    /** The response code and messages related to any requested transition. */
    public var transition: AllOfCreatedIssueTransition?
    /** The response code and messages related to any requested watchers. */
    public var watchers: AllOfCreatedIssueWatchers?

    public init(_id: String? = nil, key: String? = nil, _self: String? = nil, transition: AllOfCreatedIssueTransition? = nil, watchers: AllOfCreatedIssueWatchers? = nil) {
        self._id = _id
        self.key = key
        self._self = _self
        self.transition = transition
        self.watchers = watchers
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case key
        case _self = "self"
        case transition
        case watchers
    }

}
