//
// CreatePrioritySchemeDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a new priority scheme */

public struct CreatePrioritySchemeDetails: Codable {

    /** The ID of the default priority for the priority scheme. */
    public var defaultPriorityId: Int64
    /** The description of the priority scheme. */
    public var _description: String?
    /** Mappings of issue priorities for issues being migrated in and out of this priority scheme. */
    public var mappings: AllOfCreatePrioritySchemeDetailsMappings?
    /** The name of the priority scheme. Must be unique. */
    public var name: String
    /** The IDs of priorities in the scheme. */
    public var priorityIds: [Int64]
    /** The IDs of projects that will use the priority scheme. */
    public var projectIds: [Int64]?

    public init(defaultPriorityId: Int64, _description: String? = nil, mappings: AllOfCreatePrioritySchemeDetailsMappings? = nil, name: String, priorityIds: [Int64], projectIds: [Int64]? = nil) {
        self.defaultPriorityId = defaultPriorityId
        self._description = _description
        self.mappings = mappings
        self.name = name
        self.priorityIds = priorityIds
        self.projectIds = projectIds
    }

    public enum CodingKeys: String, CodingKey { 
        case defaultPriorityId
        case _description = "description"
        case mappings
        case name
        case priorityIds
        case projectIds
    }

}
