//
// CustomFieldContextDefaultValueFloat.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Default value for a float (number) custom field. */

public struct CustomFieldContextDefaultValueFloat: Codable {

    /** The default floating-point number. */
    public var number: Double
    public var type: String

    public init(number: Double, type: String) {
        self.number = number
        self.type = type
    }


}
