//
// CustomFieldContextDefaultValueSingleOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The default value for a single select custom field. */

public struct CustomFieldContextDefaultValueSingleOption: Codable {

    /** The ID of the context. */
    public var contextId: String
    /** The ID of the default option. */
    public var optionId: String
    public var type: String

    public init(contextId: String, optionId: String, type: String) {
        self.contextId = contextId
        self.optionId = optionId
        self.type = type
    }


}
