//
// CustomFieldContextDefaultValueForgeStringField.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The default text for a Forge string custom field. */

public struct CustomFieldContextDefaultValueForgeStringField: Codable {

    /** The ID of the context. */
    public var contextId: String
    /** The default text. The maximum length is 254 characters. */
    public var text: String?
    public var type: String

    public init(contextId: String, text: String? = nil, type: String) {
        self.contextId = contextId
        self.text = text
        self.type = type
    }


}
