//
// CustomFieldContextDefaultValueMultipleOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The default value for a multi-select custom field. */

public struct CustomFieldContextDefaultValueMultipleOption: Codable {

    /** The ID of the context. */
    public var contextId: String
    /** The list of IDs of the default options. */
    public var optionIds: [String]
    public var type: String

    public init(contextId: String, optionIds: [String], type: String) {
        self.contextId = contextId
        self.optionIds = optionIds
        self.type = type
    }


}
