//
// CustomFieldContextDefaultValueSingleVersionPicker.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The default value for a version picker custom field. */

public struct CustomFieldContextDefaultValueSingleVersionPicker: Codable {

    public var type: String
    /** The ID of the default version. */
    public var versionId: String
    /** The order the pickable versions are displayed in. If not provided, the released-first order is used. Available version orders are &#x60;\&quot;releasedFirst\&quot;&#x60; and &#x60;\&quot;unreleasedFirst\&quot;&#x60;. */
    public var versionOrder: String?

    public init(type: String, versionId: String, versionOrder: String? = nil) {
        self.type = type
        self.versionId = versionId
        self.versionOrder = versionOrder
    }


}
