//
// CustomFieldOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a custom option for a field. */

public struct CustomFieldOption {

    /** The URL of these custom field option details. */
    public var _self: String?
    /** The value of the custom field option. */
    public var value: String?

    public init(_self: String? = nil, value: String? = nil) {
        self._self = _self
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case _self = "self"
        case value
    }

}
