//
// CustomFieldContextDefaultValueDateTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The default value for a date time custom field. */

public struct CustomFieldContextDefaultValueDateTime: Codable {

    /** The default date-time in ISO format. Ignored if &#x60;useCurrent&#x60; is true. */
    public var dateTime: String?
    public var type: String
    /** Whether to use the current date. */
    public var useCurrent: Bool?

    public init(dateTime: String? = nil, type: String, useCurrent: Bool? = nil) {
        self.dateTime = dateTime
        self.type = type
        self.useCurrent = useCurrent
    }


}
