//
// CustomFieldOptionUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a custom field option for a context. */

public struct CustomFieldOptionUpdate {

    /** Whether the option is disabled. */
    public var disabled: Bool?
    /** The ID of the custom field option. */
    public var _id: String
    /** The value of the custom field option. */
    public var value: String?

    public init(disabled: Bool? = nil, _id: String, value: String? = nil) {
        self.disabled = disabled
        self._id = _id
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case disabled
        case _id = "id"
        case value
    }

}
