//
// CustomFieldOptionCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a custom field option to create. */

public struct CustomFieldOptionCreate {

    /** Whether the option is disabled. */
    public var disabled: Bool?
    /** For cascading options, the ID of the custom field object containing the cascading option. */
    public var optionId: String?
    /** The value of the custom field option. */
    public var value: String

    public init(disabled: Bool? = nil, optionId: String? = nil, value: String) {
        self.disabled = disabled
        self.optionId = optionId
        self.value = value
    }


}
