//
// DashboardDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a dashboard. */

public struct DashboardDetails: Codable {

    /** The description of the dashboard. */
    public var _description: String?
    /** The edit permissions for the dashboard. */
    public var editPermissions: [SharePermission]
    /** The name of the dashboard. */
    public var name: String
    /** The share permissions for the dashboard. */
    public var sharePermissions: [SharePermission]

    public init(_description: String? = nil, editPermissions: [SharePermission], name: String, sharePermissions: [SharePermission]) {
        self._description = _description
        self.editPermissions = editPermissions
        self.name = name
        self.sharePermissions = sharePermissions
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case editPermissions
        case name
        case sharePermissions
    }

}
