//
// DashboardGadget.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a gadget. */

public struct DashboardGadget: Codable {

    public enum Color: String, Codable { 
        case blue = "blue"
        case red = "red"
        case yellow = "yellow"
        case green = "green"
        case cyan = "cyan"
        case purple = "purple"
        case gray = "gray"
        case white = "white"
    }
    /** The color of the gadget. Should be one of &#x60;blue&#x60;, &#x60;red&#x60;, &#x60;yellow&#x60;, &#x60;green&#x60;, &#x60;cyan&#x60;, &#x60;purple&#x60;, &#x60;gray&#x60;, or &#x60;white&#x60;. */
    public var color: Color
    /** The ID of the gadget instance. */
    public var _id: Int64
    /** The module key of the gadget type. */
    public var moduleKey: String?
    /** The position of the gadget. */
    public var position: AllOfDashboardGadgetPosition
    /** The title of the gadget. */
    public var title: String
    /** The URI of the gadget type. */
    public var uri: String?

    public init(color: Color, _id: Int64, moduleKey: String? = nil, position: AllOfDashboardGadgetPosition, title: String, uri: String? = nil) {
        self.color = color
        self._id = _id
        self.moduleKey = moduleKey
        self.position = position
        self.title = title
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey { 
        case color
        case _id = "id"
        case moduleKey
        case position
        case title
        case uri
    }

}
