//
// DashboardGadgetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of gadgets on the dashboard. */

public struct DashboardGadgetResponse: Codable {

    /** The list of gadgets. */
    public var gadgets: [DashboardGadget]

    public init(gadgets: [DashboardGadget]) {
        self.gadgets = gadgets
    }


}
