//
// DateRangeFilterRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List issues archived within a specified date range. */

public struct DateRangeFilterRequest {

    /** List issues archived after a specified date, passed in the YYYY-MM-DD format. */
    public var dateAfter: String
    /** List issues archived before a specified date provided in the YYYY-MM-DD format. */
    public var dateBefore: String

    public init(dateAfter: String, dateBefore: String) {
        self.dateAfter = dateAfter
        self.dateBefore = dateBefore
    }


}
