//
// DefaultShareScope.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the scope of the default sharing for new filters and dashboards. */

public struct DefaultShareScope: Codable {

    public enum Scope: String, Codable { 
        case global = "GLOBAL"
        case authenticated = "AUTHENTICATED"
        case _private = "PRIVATE"
    }
    /** The scope of the default sharing for new filters and dashboards:   *  &#x60;AUTHENTICATED&#x60; Shared with all logged-in users.  *  &#x60;GLOBAL&#x60; Shared with all logged-in users. This shows as &#x60;AUTHENTICATED&#x60; in the response.  *  &#x60;PRIVATE&#x60; Not shared with any users. */
    public var scope: Scope

    public init(scope: Scope) {
        self.scope = scope
    }


}
