//
// DeprecatedWorkflow.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a workflow. */

public struct DeprecatedWorkflow: Codable {

    public var _default: Bool?
    /** The description of the workflow. */
    public var _description: String?
    /** The datetime the workflow was last modified. */
    public var lastModifiedDate: String?
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    public var lastModifiedUser: String?
    /** The account ID of the user that last modified the workflow. */
    public var lastModifiedUserAccountId: String?
    /** The name of the workflow. */
    public var name: String?
    /** The scope where this workflow applies */
    public var scope: AllOfDeprecatedWorkflowScope?
    /** The number of steps included in the workflow. */
    public var steps: Int?

    public init(_default: Bool? = nil, _description: String? = nil, lastModifiedDate: String? = nil, lastModifiedUser: String? = nil, lastModifiedUserAccountId: String? = nil, name: String? = nil, scope: AllOfDeprecatedWorkflowScope? = nil, steps: Int? = nil) {
        self._default = _default
        self._description = _description
        self.lastModifiedDate = lastModifiedDate
        self.lastModifiedUser = lastModifiedUser
        self.lastModifiedUserAccountId = lastModifiedUserAccountId
        self.name = name
        self.scope = scope
        self.steps = steps
    }

    public enum CodingKeys: String, CodingKey { 
        case _default = "default"
        case _description = "description"
        case lastModifiedDate
        case lastModifiedUser
        case lastModifiedUserAccountId
        case name
        case scope
        case steps
    }

}
