//
// Errors.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Errors {

    public var issueIsSubtask: ModelError?
    public var issuesInArchivedProjects: ModelError?
    public var issuesInUnlicensedProjects: ModelError?
    public var issuesNotFound: ModelError?
    public var userDoesNotHavePermission: ModelError?

    public init(issueIsSubtask: ModelError? = nil, issuesInArchivedProjects: ModelError? = nil, issuesInUnlicensedProjects: ModelError? = nil, issuesNotFound: ModelError? = nil, userDoesNotHavePermission: ModelError? = nil) {
        self.issueIsSubtask = issueIsSubtask
        self.issuesInArchivedProjects = issuesInArchivedProjects
        self.issuesInUnlicensedProjects = issuesInUnlicensedProjects
        self.issuesNotFound = issuesNotFound
        self.userDoesNotHavePermission = userDoesNotHavePermission
    }


}
