//
// FieldDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a field. */

public struct FieldDetails: Codable {

    /** The names that can be used to reference the field in an advanced search. For more information, see [Advanced searching - fields reference](https://confluence.atlassian.com/x/gwORLQ). */
    public var clauseNames: [String]?
    /** Whether the field is a custom field. */
    public var custom: Bool?
    /** The ID of the field. */
    public var _id: String?
    /** The key of the field. */
    public var key: String?
    /** The name of the field. */
    public var name: String?
    /** Whether the field can be used as a column on the issue navigator. */
    public var navigable: Bool?
    /** Whether the content of the field can be used to order lists. */
    public var orderable: Bool?
    /** The data schema for the field. */
    public var schema: AllOfFieldDetailsSchema?
    /** The scope of the field. */
    public var scope: AllOfFieldDetailsScope?
    /** Whether the content of the field can be searched. */
    public var searchable: Bool?

    public init(clauseNames: [String]? = nil, custom: Bool? = nil, _id: String? = nil, key: String? = nil, name: String? = nil, navigable: Bool? = nil, orderable: Bool? = nil, schema: AllOfFieldDetailsSchema? = nil, scope: AllOfFieldDetailsScope? = nil, searchable: Bool? = nil) {
        self.clauseNames = clauseNames
        self.custom = custom
        self._id = _id
        self.key = key
        self.name = name
        self.navigable = navigable
        self.orderable = orderable
        self.schema = schema
        self.scope = scope
        self.searchable = searchable
    }

    public enum CodingKeys: String, CodingKey { 
        case clauseNames
        case custom
        case _id = "id"
        case key
        case name
        case navigable
        case orderable
        case schema
        case scope
        case searchable
    }

}
