//
// FieldConfigurationSchemeProjects.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Project list with assigned field configuration schema. */

public struct FieldConfigurationSchemeProjects: Codable {

    public var fieldConfigurationScheme: FieldConfigurationScheme?
    /** The IDs of projects using the field configuration scheme. */
    public var projectIds: [String]

    public init(fieldConfigurationScheme: FieldConfigurationScheme? = nil, projectIds: [String]) {
        self.fieldConfigurationScheme = fieldConfigurationScheme
        self.projectIds = projectIds
    }


}
