//
// FieldConfigurationIssueTypeItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The field configuration for an issue type. */

public struct FieldConfigurationIssueTypeItem: Codable {

    /** The ID of the field configuration. */
    public var fieldConfigurationId: String
    /** The ID of the field configuration scheme. */
    public var fieldConfigurationSchemeId: String
    /** The ID of the issue type or *default*. When set to *default* this field configuration issue type item applies to all issue types without a field configuration. */
    public var issueTypeId: String

    public init(fieldConfigurationId: String, fieldConfigurationSchemeId: String, issueTypeId: String) {
        self.fieldConfigurationId = fieldConfigurationId
        self.fieldConfigurationSchemeId = fieldConfigurationSchemeId
        self.issueTypeId = issueTypeId
    }


}
