//
// FieldReferenceData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a field that can be used in advanced searches. */

public struct FieldReferenceData: Codable {

    public enum Auto: String, Codable { 
        case _true = "true"
        case _false = "false"
    }
    public enum Deprecated: String, Codable { 
        case _true = "true"
        case _false = "false"
    }
    public enum Orderable: String, Codable { 
        case _true = "true"
        case _false = "false"
    }
    public enum Searchable: String, Codable { 
        case _true = "true"
        case _false = "false"
    }
    /** Whether the field provide auto-complete suggestions. */
    public var auto: Auto?
    /** If the item is a custom field, the ID of the custom field. */
    public var cfid: String?
    /** Whether this field has been deprecated. */
    public var deprecated: Deprecated?
    /** The searcher key of the field, only passed when the field is deprecated. */
    public var deprecatedSearcherKey: String?
    /** The display name contains the following:   *  for system fields, the field name. For example, &#x60;Summary&#x60;.  *  for collapsed custom fields, the field name followed by a hyphen and then the field name and field type. For example, &#x60;Component - Component[Dropdown]&#x60;.  *  for other custom fields, the field name followed by a hyphen and then the custom field ID. For example, &#x60;Component - cf[10061]&#x60;. */
    public var displayName: String?
    /** The valid search operators for the field. */
    public var operators: [String]?
    /** Whether the field can be used in a query&#x27;s &#x60;ORDER BY&#x60; clause. */
    public var orderable: Orderable?
    /** Whether the content of this field can be searched. */
    public var searchable: Searchable?
    /** The data types of items in the field. */
    public var types: [String]?
    /** The field identifier. */
    public var value: String?

    public init(auto: Auto? = nil, cfid: String? = nil, deprecated: Deprecated? = nil, deprecatedSearcherKey: String? = nil, displayName: String? = nil, operators: [String]? = nil, orderable: Orderable? = nil, searchable: Searchable? = nil, types: [String]? = nil, value: String? = nil) {
        self.auto = auto
        self.cfid = cfid
        self.deprecated = deprecated
        self.deprecatedSearcherKey = deprecatedSearcherKey
        self.displayName = displayName
        self.operators = operators
        self.orderable = orderable
        self.searchable = searchable
        self.types = types
        self.value = value
    }


}
