//
// FoundGroups.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of groups found in a search, including header text (Showing X of Y matching groups) and total of matched groups. */

public struct FoundGroups: Codable {

    public var groups: [FoundGroup]?
    /** Header text indicating the number of groups in the response and the total number of groups found in the search. */
    public var header: String?
    /** The total number of groups found in the search. */
    public var total: Int?

    public init(groups: [FoundGroup]? = nil, header: String? = nil, total: Int? = nil) {
        self.groups = groups
        self.header = header
        self.total = total
    }


}
