//
// FoundUsers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of users found in a search, including header text (Showing X of Y matching users) and total of matched users. */

public struct FoundUsers: Codable {

    /** Header text indicating the number of users in the response and the total number of users found in the search. */
    public var header: String?
    /** The total number of users found in the search. */
    public var total: Int?
    public var users: [UserPickerUser]?

    public init(header: String? = nil, total: Int? = nil, users: [UserPickerUser]? = nil) {
        self.header = header
        self.total = total
        self.users = users
    }


}
