//
// FunctionReferenceData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of functions that can be used in advanced searches. */

public struct FunctionReferenceData {

    public enum IsList: String, Codable { 
        case _true = "true"
        case _false = "false"
    }
    public enum SupportsListAndSingleValueOperators: String, Codable { 
        case _true = "true"
        case _false = "false"
    }
    /** The display name of the function. */
    public var displayName: String?
    /** Whether the function can take a list of arguments. */
    public var isList: IsList?
    /** Whether the function supports both single and list value operators. */
    public var supportsListAndSingleValueOperators: SupportsListAndSingleValueOperators?
    /** The data types returned by the function. */
    public var types: [String]?
    /** The function identifier. */
    public var value: String?

    public init(displayName: String? = nil, isList: IsList? = nil, supportsListAndSingleValueOperators: SupportsListAndSingleValueOperators? = nil, types: [String]? = nil, value: String? = nil) {
        self.displayName = displayName
        self.isList = isList
        self.supportsListAndSingleValueOperators = supportsListAndSingleValueOperators
        self.types = types
        self.value = value
    }


}
