//
// IconBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An icon. */

public struct IconBean: Codable {

    /** The URL of the tooltip, used only for a status icon. */
    public var link: String?
    /** The title of the icon, for use as a tooltip on the icon. */
    public var title: String?
    /** The URL of a 16x16 pixel icon. */
    public var url16x16: String?

    public init(link: String? = nil, title: String? = nil, url16x16: String? = nil) {
        self.link = link
        self.title = title
        self.url16x16 = url16x16
    }


}
