//
// IssueMatches.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of matched issues or errors for each JQL query, in the order the JQL queries were passed. */

public struct IssueMatches: Codable {

    public var matches: [IssueMatchesForJQL]

    public init(matches: [IssueMatchesForJQL]) {
        self.matches = matches
    }


}
