//
// IssuesJqlMetaDataBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The description of the page of issues loaded by the provided JQL query. */

public struct IssuesJqlMetaDataBean: Codable {

    /** The number of issues that were loaded in this evaluation. */
    public var count: Int
    /** The maximum number of issues that could be loaded in this evaluation. */
    public var maxResults: Int
    /** The index of the first issue. */
    public var startAt: Int64
    /** The total number of issues the JQL returned. */
    public var totalCount: Int64
    /** Any warnings related to the JQL query. Present only if the validation mode was set to &#x60;warn&#x60;. */
    public var validationWarnings: [String]?

    public init(count: Int, maxResults: Int, startAt: Int64, totalCount: Int64, validationWarnings: [String]? = nil) {
        self.count = count
        self.maxResults = maxResults
        self.startAt = startAt
        self.totalCount = totalCount
        self.validationWarnings = validationWarnings
    }


}
