//
// IssueTypeScreenSchemeDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The details of an issue type screen scheme. */

public struct IssueTypeScreenSchemeDetails: Codable {

    /** The description of the issue type screen scheme. The maximum length is 255 characters. */
    public var _description: String?
    /** The IDs of the screen schemes for the issue type IDs and *default*. A *default* entry is required to create an issue type screen scheme, it defines the mapping for all issue types without a screen scheme. */
    public var issueTypeMappings: [IssueTypeScreenSchemeMapping]
    /** The name of the issue type screen scheme. The name must be unique. The maximum length is 255 characters. */
    public var name: String

    public init(_description: String? = nil, issueTypeMappings: [IssueTypeScreenSchemeMapping], name: String) {
        self._description = _description
        self.issueTypeMappings = issueTypeMappings
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case issueTypeMappings
        case name
    }

}
