//
// IssueSecurityLevelMember.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Issue security level member. */

public struct IssueSecurityLevelMember: Codable {

    /** The user or group being granted the permission. It consists of a &#x60;type&#x60; and a type-dependent &#x60;parameter&#x60;. See [Holder object](../api-group-permission-schemes/#holder-object) in *Get all permission schemes* for more information. */
    public var holder: AllOfIssueSecurityLevelMemberHolder
    /** The ID of the issue security level member. */
    public var _id: Int64
    /** The ID of the issue security level. */
    public var issueSecurityLevelId: Int64
    public var managed: Bool?

    public init(holder: AllOfIssueSecurityLevelMemberHolder, _id: Int64, issueSecurityLevelId: Int64, managed: Bool? = nil) {
        self.holder = holder
        self._id = _id
        self.issueSecurityLevelId = issueSecurityLevelId
        self.managed = managed
    }

    public enum CodingKeys: String, CodingKey { 
        case holder
        case _id = "id"
        case issueSecurityLevelId
        case managed
    }

}
