//
// IssueLinkTypes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of issue link type beans. */

public struct IssueLinkTypes {

    /** The issue link type bean. */
    public var issueLinkTypes: [IssueLinkType]?

    public init(issueLinkTypes: [IssueLinkType]? = nil) {
        self.issueLinkTypes = issueLinkTypes
    }


}
