//
// IssueArchivalSyncRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List of Issue Ids Or Keys that are to be archived or unarchived */

public struct IssueArchivalSyncRequest: Codable {

    public var issueIdsOrKeys: [String]?

    public init(issueIdsOrKeys: [String]? = nil) {
        self.issueIdsOrKeys = issueIdsOrKeys
    }


}
