//
// IssueFieldOptionConfiguration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the projects the option is available in. */

public struct IssueFieldOptionConfiguration {

    public enum Attributes: String, Codable { 
        case notselectable = "notSelectable"
        case defaultvalue = "defaultValue"
    }
    /** DEPRECATED */
    public var attributes: [Attributes]?
    /** Defines the projects that the option is available in. If the scope is not defined, then the option is available in all projects. */
    public var scope: AllOfIssueFieldOptionConfigurationScope?

    public init(attributes: [Attributes]? = nil, scope: AllOfIssueFieldOptionConfigurationScope? = nil) {
        self.attributes = attributes
        self.scope = scope
    }


}
