//
// IssueChangelogIds.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of changelog IDs. */

public struct IssueChangelogIds: Codable {

    /** The list of changelog IDs. */
    public var changelogIds: [Int64]

    public init(changelogIds: [Int64]) {
        self.changelogIds = changelogIds
    }


}
