//
// IssueTypeSchemeID.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The ID of an issue type scheme. */

public struct IssueTypeSchemeID {

    /** The ID of the issue type scheme. */
    public var issueTypeSchemeId: String

    public init(issueTypeSchemeId: String) {
        self.issueTypeSchemeId = issueTypeSchemeId
    }


}
