//
// IssueCommentListRequestBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IssueCommentListRequestBean: Codable {

    /** The list of comment IDs. A maximum of 1000 IDs can be specified. */
    public var ids: [Int64]

    public init(ids: [Int64]) {
        self.ids = ids
    }


}
