//
// IssueMatchesForJQL.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of the issues matched to a JQL query or details of errors encountered during matching. */

public struct IssueMatchesForJQL: Codable {

    /** A list of errors. */
    public var errors: [String]
    /** A list of issue IDs. */
    public var matchedIssues: [Int64]

    public init(errors: [String], matchedIssues: [Int64]) {
        self.errors = errors
        self.matchedIssues = matchedIssues
    }


}
