//
// IssueTypeSchemeDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of an issue type scheme and its associated issue types. */

public struct IssueTypeSchemeDetails {

    /** The ID of the default issue type of the issue type scheme. This ID must be included in &#x60;issueTypeIds&#x60;. */
    public var defaultIssueTypeId: String?
    /** The description of the issue type scheme. The maximum length is 4000 characters. */
    public var _description: String?
    /** The list of issue types IDs of the issue type scheme. At least one standard issue type ID is required. */
    public var issueTypeIds: [String]
    /** The name of the issue type scheme. The name must be unique. The maximum length is 255 characters. */
    public var name: String

    public init(defaultIssueTypeId: String? = nil, _description: String? = nil, issueTypeIds: [String], name: String) {
        self.defaultIssueTypeId = defaultIssueTypeId
        self._description = _description
        self.issueTypeIds = issueTypeIds
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case defaultIssueTypeId
        case _description = "description"
        case issueTypeIds
        case name
    }

}
