//
// IssueCreateMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The wrapper for the issue creation metadata for a list of projects. */

public struct IssueCreateMetadata {

    /** Expand options that include additional project details in the response. */
    public var expand: String?
    /** List of projects and their issue creation metadata. */
    public var projects: [ProjectIssueCreateMetadata]?

    public init(expand: String? = nil, projects: [ProjectIssueCreateMetadata]? = nil) {
        self.expand = expand
        self.projects = projects
    }


}
