//
// IssueTypeIssueCreateMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the issue creation metadata for an issue type. */

public struct IssueTypeIssueCreateMetadata: Codable {

    /** The ID of the issue type&#x27;s avatar. */
    public var avatarId: Int64?
    /** The description of the issue type. */
    public var _description: String?
    /** Unique ID for next-gen projects. */
    public var entityId: UUID?
    /** Expand options that include additional issue type metadata details in the response. */
    public var expand: String?
    /** List of the fields available when creating an issue for the issue type. */
    public var fields: [String:FieldMetadata]?
    /** Hierarchy level of the issue type. */
    public var hierarchyLevel: Int?
    /** The URL of the issue type&#x27;s avatar. */
    public var iconUrl: String?
    /** The ID of the issue type. */
    public var _id: String?
    /** The name of the issue type. */
    public var name: String?
    /** Details of the next-gen projects the issue type is available in. */
    public var scope: AllOfIssueTypeIssueCreateMetadataScope?
    /** The URL of these issue type details. */
    public var _self: String?
    /** Whether this issue type is used to create subtasks. */
    public var subtask: Bool?

    public init(avatarId: Int64? = nil, _description: String? = nil, entityId: UUID? = nil, expand: String? = nil, fields: [String:FieldMetadata]? = nil, hierarchyLevel: Int? = nil, iconUrl: String? = nil, _id: String? = nil, name: String? = nil, scope: AllOfIssueTypeIssueCreateMetadataScope? = nil, _self: String? = nil, subtask: Bool? = nil) {
        self.avatarId = avatarId
        self._description = _description
        self.entityId = entityId
        self.expand = expand
        self.fields = fields
        self.hierarchyLevel = hierarchyLevel
        self.iconUrl = iconUrl
        self._id = _id
        self.name = name
        self.scope = scope
        self._self = _self
        self.subtask = subtask
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarId
        case _description = "description"
        case entityId
        case expand
        case fields
        case hierarchyLevel
        case iconUrl
        case _id = "id"
        case name
        case scope
        case _self = "self"
        case subtask
    }

}
