//
// IssueTypeWithStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Status details for an issue type. */

public struct IssueTypeWithStatus: Codable {

    /** The ID of the issue type. */
    public var _id: String
    /** The name of the issue type. */
    public var name: String
    /** The URL of the issue type&#x27;s status details. */
    public var _self: String
    /** List of status details for the issue type. */
    public var statuses: [StatusDetails]
    /** Whether this issue type represents subtasks. */
    public var subtask: Bool

    public init(_id: String, name: String, _self: String, statuses: [StatusDetails], subtask: Bool) {
        self._id = _id
        self.name = name
        self._self = _self
        self.statuses = statuses
        self.subtask = subtask
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _self = "self"
        case statuses
        case subtask
    }

}
