//
// IssueTypeInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of an issue type. */

public struct IssueTypeInfo: Codable {

    /** The avatar of the issue type. */
    public var avatarId: Int64?
    /** The ID of the issue type. */
    public var _id: Int64?
    /** The name of the issue type. */
    public var name: String?

    public init(avatarId: Int64? = nil, _id: Int64? = nil, name: String? = nil) {
        self.avatarId = avatarId
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarId
        case _id = "id"
        case name
    }

}
