//
// IssuesAndJQLQueries.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List of issues and JQL queries. */

public struct IssuesAndJQLQueries: Codable {

    /** A list of issue IDs. */
    public var issueIds: [Int64]
    /** A list of JQL queries. */
    public var jqls: [String]

    public init(issueIds: [Int64], jqls: [String]) {
        self.issueIds = issueIds
        self.jqls = jqls
    }


}
