//
// JExpEvaluateMetaDataBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information about the expression evaluation. This bean will be replacing &#x60;JiraExpressionEvaluationMetaDataBean&#x60; bean as part of new &#x60;evaluate&#x60; endpoint */

public struct JExpEvaluateMetaDataBean: Codable {

    /** Contains information about the expression complexity. For example, the number of steps it took to evaluate the expression. */
    public var complexity: AllOfJExpEvaluateMetaDataBeanComplexity?
    /** Contains information about the &#x60;issues&#x60; variable in the context. For example, is the issues were loaded with JQL, information about the page will be included here. */
    public var issues: AllOfJExpEvaluateMetaDataBeanIssues?

    public init(complexity: AllOfJExpEvaluateMetaDataBeanComplexity? = nil, issues: AllOfJExpEvaluateMetaDataBeanIssues? = nil) {
        self.complexity = complexity
        self.issues = issues
    }


}
