//
// JiraExpressionAnalysis.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the analysed Jira expression. */

public struct JiraExpressionAnalysis: Codable {

    public var complexity: JiraExpressionComplexity?
    /** A list of validation errors. Not included if the expression is valid. */
    public var errors: [JiraExpressionValidationError]?
    /** The analysed expression. */
    public var expression: String
    /** EXPERIMENTAL. The inferred type of the expression. */
    public var type: String?
    /** Whether the expression is valid and the interpreter will evaluate it. Note that the expression may fail at runtime (for example, if it executes too many expensive operations). */
    public var valid: Bool

    public init(complexity: JiraExpressionComplexity? = nil, errors: [JiraExpressionValidationError]? = nil, expression: String, type: String? = nil, valid: Bool) {
        self.complexity = complexity
        self.errors = errors
        self.expression = expression
        self.type = type
        self.valid = valid
    }


}
