//
// JiraExpressionEvaluateRequestBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The request to evaluate a Jira expression. This bean will be replacing &#x60;JiraExpressionEvaluateRequest&#x60; as part of new &#x60;evaluate&#x60; endpoint */

public struct JiraExpressionEvaluateRequestBean: Codable {

    /** The context in which the Jira expression is evaluated. */
    public var context: AllOfJiraExpressionEvaluateRequestBeanContext?
    /** The Jira expression to evaluate. */
    public var expression: String

    public init(context: AllOfJiraExpressionEvaluateRequestBeanContext? = nil, expression: String) {
        self.context = context
        self.expression = expression
    }


}
