//
// JiraExpressionResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The result of evaluating a Jira expression. */

public struct JiraExpressionResult: Codable {

    /** Contains various characteristics of the performed expression evaluation. */
    public var meta: AllOfJiraExpressionResultMeta?
    /** The value of the evaluated expression. It may be a primitive JSON value or a Jira REST API object. (Some expressions do not produce any meaningful results—for example, an expression that returns a lambda function—if that&#x27;s the case a simple string representation is returned. These string representations should not be relied upon and may change without notice.) */
    public var value: Any

    public init(meta: AllOfJiraExpressionResultMeta? = nil, value: Any) {
        self.meta = meta
        self.value = value
    }


}
