//
// JQLCountRequestBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JQLCountRequestBean: Codable {

    /** A [JQL](https://confluence.atlassian.com/x/egORLQ) expression. For performance reasons, this field requires a bounded query. A bounded query is a query with a search restriction. */
    public var jql: String?

    public init(jql: String? = nil) {
        self.jql = jql
    }


}
