//
// JqlQueryClause.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A JQL query clause. */

public struct JqlQueryClause: Codable {




}
