//
// JqlQueryClauseOperand.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of an operand in a JQL clause. */

public struct JqlQueryClauseOperand {




}
