//
// JqlQueriesToSanitize.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of JQL queries to sanitize for the given account IDs. */

public struct JqlQueriesToSanitize: Codable {

    /** The list of JQL queries to sanitize. Must contain unique values. Maximum of 20 queries. */
    public var queries: [JqlQueryToSanitize]

    public init(queries: [JqlQueryToSanitize]) {
        self.queries = queries
    }


}
