//
// JqlQueriesToParse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of JQL queries to parse. */

public struct JqlQueriesToParse: Codable {

    /** A list of queries to parse. */
    public var queries: [String]

    public init(queries: [String]) {
        self.queries = queries
    }


}
