//
// LegacyJackson1ListVersion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public typealias LegacyJackson1ListVersion = [Version]