//
// LicensedApplication.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a licensed Jira application. */

public struct LicensedApplication: Codable {

    public enum Plan: String, Codable { 
        case unlicensed = "UNLICENSED"
        case free = "FREE"
        case paid = "PAID"
    }
    /** The ID of the application. */
    public var _id: String
    /** The licensing plan. */
    public var plan: Plan

    public init(_id: String, plan: Plan) {
        self._id = _id
        self.plan = plan
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case plan
    }

}
