//
// LicenseMetric.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A metric that provides insight into the active licence details */

public struct LicenseMetric: Codable {

    /** The key of a specific license metric. */
    public var key: String?
    /** The calculated value of a licence metric linked to the key. An example licence metric is the approximate number of user accounts. */
    public var value: String?

    public init(key: String? = nil, value: String? = nil) {
        self.key = key
        self.value = value
    }


}
