//
// LinkIssueRequestJsonBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LinkIssueRequestJsonBean: Codable {

    public var comment: Comment?
    public var inwardIssue: LinkedIssue
    public var outwardIssue: LinkedIssue
    public var type: IssueLinkType

    public init(comment: Comment? = nil, inwardIssue: LinkedIssue, outwardIssue: LinkedIssue, type: IssueLinkType) {
        self.comment = comment
        self.inwardIssue = inwardIssue
        self.outwardIssue = outwardIssue
        self.type = type
    }


}
