//
// MoveFieldBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MoveFieldBean: Codable {

    public enum Position: String, Codable { 
        case earlier = "Earlier"
        case later = "Later"
        case first = "First"
        case last = "Last"
    }
    /** The ID of the screen tab field after which to place the moved screen tab field. Required if &#x60;position&#x60; isn&#x27;t provided. */
    public var after: String?
    /** The named position to which the screen tab field should be moved. Required if &#x60;after&#x60; isn&#x27;t provided. */
    public var position: Position?

    public init(after: String? = nil, position: Position? = nil) {
        self.after = after
        self.position = position
    }


}
