//
// NestedResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NestedResponse: Codable {

    public var errorCollection: ErrorCollection?
    public var status: Int?
    public var warningCollection: WarningCollection?

    public init(errorCollection: ErrorCollection? = nil, status: Int? = nil, warningCollection: WarningCollection? = nil) {
        self.errorCollection = errorCollection
        self.status = status
        self.warningCollection = warningCollection
    }


}
