//
// NewUserDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The user details. */

public struct NewUserDetails: Codable {




}
