//
// NotificationSchemeEventTypeId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The ID of an event that is being mapped to notifications. */

public struct NotificationSchemeEventTypeId: Codable {




}
