//
// NotificationSchemeAndProjectMappingJsonBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NotificationSchemeAndProjectMappingJsonBean {

    public var notificationSchemeId: String?
    public var projectId: String?

    public init(notificationSchemeId: String? = nil, projectId: String? = nil) {
        self.notificationSchemeId = notificationSchemeId
        self.projectId = projectId
    }


}
