//
// NotificationSchemeEventDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a notification scheme event. */

public struct NotificationSchemeEventDetails: Codable {




}
