//
// OrderOfCustomFieldOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An ordered list of custom field option IDs and information on where to move them. */

public struct OrderOfCustomFieldOptions: Codable {

    public enum Position: String, Codable { 
        case first = "First"
        case last = "Last"
    }
    /** The ID of the custom field option or cascading option to place the moved options after. Required if &#x60;position&#x60; isn&#x27;t provided. */
    public var after: String?
    /** A list of IDs of custom field options to move. The order of the custom field option IDs in the list is the order they are given after the move. The list must contain custom field options or cascading options, but not both. */
    public var customFieldOptionIds: [String]
    /** The position the custom field options should be moved to. Required if &#x60;after&#x60; isn&#x27;t provided. */
    public var position: Position?

    public init(after: String? = nil, customFieldOptionIds: [String], position: Position? = nil) {
        self.after = after
        self.customFieldOptionIds = customFieldOptionIds
        self.position = position
    }


}
