//
// PageOfDashboards.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A page containing dashboard details. */

public struct PageOfDashboards {

    /** List of dashboards. */
    public var dashboards: [Dashboard]?
    /** The maximum number of results that could be on the page. */
    public var maxResults: Int?
    /** The URL of the next page of results, if any. */
    public var next: String?
    /** The URL of the previous page of results, if any. */
    public var prev: String?
    /** The index of the first item returned on the page. */
    public var startAt: Int?
    /** The number of results on the page. */
    public var total: Int?

    public init(dashboards: [Dashboard]? = nil, maxResults: Int? = nil, next: String? = nil, prev: String? = nil, startAt: Int? = nil, total: Int? = nil) {
        self.dashboards = dashboards
        self.maxResults = maxResults
        self.next = next
        self.prev = prev
        self.startAt = startAt
        self.total = total
    }


}
