//
// PageOfWorklogs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Paginated list of worklog details */

public struct PageOfWorklogs: Codable {




}
