//
// PageOfCreateMetaIssueTypes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A page of CreateMetaIssueTypes. */

public struct PageOfCreateMetaIssueTypes: Codable {




}
