//
// PermissionGrants.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List of permission grants. */

public struct PermissionGrants {

    /** Expand options that include additional permission grant details in the response. */
    public var expand: String?
    /** Permission grants list. */
    public var permissions: [PermissionGrant]?

    public init(expand: String? = nil, permissions: [PermissionGrant]? = nil) {
        self.expand = expand
        self.permissions = permissions
    }


}
