//
// PermittedProjects.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of projects in which a user is granted permissions. */

public struct PermittedProjects: Codable {

    /** A list of projects. */
    public var projects: [ProjectIdentifierBean]?

    public init(projects: [ProjectIdentifierBean]? = nil) {
        self.projects = projects
    }


}
