//
// Permissions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about permissions. */

public struct Permissions: Codable {

    /** List of permissions. */
    public var permissions: [String:UserPermission]?

    public init(permissions: [String:UserPermission]? = nil) {
        self.permissions = permissions
    }


}
