//
// PriorityMapping.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Mapping of issue priorities for changes in priority schemes. */

public struct PriorityMapping: Codable {

    /** The mapping of priorities for issues being migrated **into** this priority scheme. Key is the old priority ID, value is the new priority ID (must exist in this priority scheme). */
    public var _in: [String:Int64]?
    /** The mapping of priorities for issues being migrated **out of** this priority scheme. Key is the old priority ID (must exist in this priority scheme), value is the new priority ID (must exist in the default priority scheme). Required for updating an existing priority scheme. Not used when creating a new priority scheme. */
    public var out: [String:Int64]?

    public init(_in: [String:Int64]? = nil, out: [String:Int64]? = nil) {
        self._in = _in
        self.out = out
    }

    public enum CodingKeys: String, CodingKey { 
        case _in = "in"
        case out
    }

}
