//
// PriorityWithSequence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An issue priority with sequence information. */

public struct PriorityWithSequence: Codable {

    /** The description of the issue priority. */
    public var _description: String?
    /** The URL of the icon for the issue priority. */
    public var iconUrl: String?
    /** The ID of the issue priority. */
    public var _id: String?
    /** Whether this priority is the default. */
    public var isDefault: Bool?
    /** The name of the issue priority. */
    public var name: String?
    /** The URL of the issue priority. */
    public var _self: String?
    /** The sequence of the issue priority. */
    public var sequence: String?
    /** The color used to indicate the issue priority. */
    public var statusColor: String?

    public init(_description: String? = nil, iconUrl: String? = nil, _id: String? = nil, isDefault: Bool? = nil, name: String? = nil, _self: String? = nil, sequence: String? = nil, statusColor: String? = nil) {
        self._description = _description
        self.iconUrl = iconUrl
        self._id = _id
        self.isDefault = isDefault
        self.name = name
        self._self = _self
        self.sequence = sequence
        self.statusColor = statusColor
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case iconUrl
        case _id = "id"
        case isDefault
        case name
        case _self = "self"
        case sequence
        case statusColor
    }

}
