//
// ProjectDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a project. */

public struct ProjectDetails: Codable {

    public enum ProjectTypeKey: String, Codable { 
        case software = "software"
        case serviceDesk = "service_desk"
        case business = "business"
    }
    /** The URLs of the project&#x27;s avatars. */
    public var avatarUrls: AllOfProjectDetailsAvatarUrls?
    /** The ID of the project. */
    public var _id: String?
    /** The key of the project. */
    public var key: String?
    /** The name of the project. */
    public var name: String?
    /** The category the project belongs to. */
    public var projectCategory: AllOfProjectDetailsProjectCategory?
    /** The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project. */
    public var projectTypeKey: ProjectTypeKey?
    /** The URL of the project details. */
    public var _self: String?
    /** Whether or not the project is simplified. */
    public var simplified: Bool?

    public init(avatarUrls: AllOfProjectDetailsAvatarUrls? = nil, _id: String? = nil, key: String? = nil, name: String? = nil, projectCategory: AllOfProjectDetailsProjectCategory? = nil, projectTypeKey: ProjectTypeKey? = nil, _self: String? = nil, simplified: Bool? = nil) {
        self.avatarUrls = avatarUrls
        self._id = _id
        self.key = key
        self.name = name
        self.projectCategory = projectCategory
        self.projectTypeKey = projectTypeKey
        self._self = _self
        self.simplified = simplified
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarUrls
        case _id = "id"
        case key
        case name
        case projectCategory
        case projectTypeKey
        case _self = "self"
        case simplified
    }

}
