//
// ProjectIssueCreateMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the issue creation metadata for a project. */

public struct ProjectIssueCreateMetadata: Codable {

    /** List of the project&#x27;s avatars, returning the avatar size and associated URL. */
    public var avatarUrls: AllOfProjectIssueCreateMetadataAvatarUrls?
    /** Expand options that include additional project issue create metadata details in the response. */
    public var expand: String?
    /** The ID of the project. */
    public var _id: String?
    /** List of the issue types supported by the project. */
    public var issuetypes: [IssueTypeIssueCreateMetadata]?
    /** The key of the project. */
    public var key: String?
    /** The name of the project. */
    public var name: String?
    /** The URL of the project. */
    public var _self: String?

    public init(avatarUrls: AllOfProjectIssueCreateMetadataAvatarUrls? = nil, expand: String? = nil, _id: String? = nil, issuetypes: [IssueTypeIssueCreateMetadata]? = nil, key: String? = nil, name: String? = nil, _self: String? = nil) {
        self.avatarUrls = avatarUrls
        self.expand = expand
        self._id = _id
        self.issuetypes = issuetypes
        self.key = key
        self.name = name
        self._self = _self
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarUrls
        case expand
        case _id = "id"
        case issuetypes
        case key
        case name
        case _self = "self"
    }

}
