//
// ProjectAndIssueTypePair.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A project and issueType ID pair that identifies a status mapping. */

public struct ProjectAndIssueTypePair: Codable {

    /** The ID of the issue type. */
    public var issueTypeId: String
    /** The ID of the project. */
    public var projectId: String

    public init(issueTypeId: String, projectId: String) {
        self.issueTypeId = issueTypeId
        self.projectId = projectId
    }


}
