//
// ProjectIssueSecurityLevels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List of issue level security items in a project. */

public struct ProjectIssueSecurityLevels: Codable {

    /** Issue level security items list. */
    public var levels: [SecurityLevel]

    public init(levels: [SecurityLevel]) {
        self.levels = levels
    }


}
