//
// RemoteIssueLink.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of an issue remote link. */

public struct RemoteIssueLink: Codable {

    /** Details of the remote application the linked item is in. */
    public var application: AllOfRemoteIssueLinkApplication?
    /** The global ID of the link, such as the ID of the item on the remote system. */
    public var globalId: String?
    /** The ID of the link. */
    public var _id: Int64?
    /** Details of the item linked to. */
    public var object: AllOfRemoteIssueLinkObject?
    /** Description of the relationship between the issue and the linked item. */
    public var relationship: String?
    /** The URL of the link. */
    public var _self: String?

    public init(application: AllOfRemoteIssueLinkApplication? = nil, globalId: String? = nil, _id: Int64? = nil, object: AllOfRemoteIssueLinkObject? = nil, relationship: String? = nil, _self: String? = nil) {
        self.application = application
        self.globalId = globalId
        self._id = _id
        self.object = object
        self.relationship = relationship
        self._self = _self
    }

    public enum CodingKeys: String, CodingKey { 
        case application
        case globalId
        case _id = "id"
        case object
        case relationship
        case _self = "self"
    }

}
