//
// RemoteObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The linked item. */

public struct RemoteObject: Codable {




}
