//
// ReorderIssueResolutionsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Change the order of issue resolutions. */

public struct ReorderIssueResolutionsRequest: Codable {

    /** The ID of the resolution. Required if &#x60;position&#x60; isn&#x27;t provided. */
    public var after: String?
    /** The list of resolution IDs to be reordered. Cannot contain duplicates nor after ID. */
    public var ids: [String]
    /** The position for issue resolutions to be moved to. Required if &#x60;after&#x60; isn&#x27;t provided. */
    public var position: String?

    public init(after: String? = nil, ids: [String], position: String? = nil) {
        self.after = after
        self.ids = ids
        self.position = position
    }


}
