//
// RequiredMappingByWorkflows.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of required status mappings by workflow. */

public struct RequiredMappingByWorkflows: Codable {

    /** The ID of the source workflow. */
    public var sourceWorkflowId: String?
    /** The status IDs requiring mapping. */
    public var statusIds: [String]?
    /** The ID of the target workflow. */
    public var targetWorkflowId: String?

    public init(sourceWorkflowId: String? = nil, statusIds: [String]? = nil, targetWorkflowId: String? = nil) {
        self.sourceWorkflowId = sourceWorkflowId
        self.statusIds = statusIds
        self.targetWorkflowId = targetWorkflowId
    }


}
