//
// ResolutionId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The ID of an issue resolution. */

public struct ResolutionId: Codable {




}
