//
// ResolutionJsonBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResolutionJsonBean: Codable {

    public var _default: Bool?
    public var _description: String?
    public var iconUrl: String?
    public var _id: String?
    public var name: String?
    public var _self: String?

    public init(_default: Bool? = nil, _description: String? = nil, iconUrl: String? = nil, _id: String? = nil, name: String? = nil, _self: String? = nil) {
        self._default = _default
        self._description = _description
        self.iconUrl = iconUrl
        self._id = _id
        self.name = name
        self._self = _self
    }

    public enum CodingKeys: String, CodingKey { 
        case _default = "default"
        case _description = "description"
        case iconUrl
        case _id = "id"
        case name
        case _self = "self"
    }

}
