//
// Resource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Resource: Codable {

    public var _description: String?
    public var file: Data?
    public var filename: String?
    public var inputStream: Any?
    public var _open: Bool?
    public var readable: Bool?
    public var uri: String?
    public var url: String?

    public init(_description: String? = nil, file: Data? = nil, filename: String? = nil, inputStream: Any? = nil, _open: Bool? = nil, readable: Bool? = nil, uri: String? = nil, url: String? = nil) {
        self._description = _description
        self.file = file
        self.filename = filename
        self.inputStream = inputStream
        self._open = _open
        self.readable = readable
        self.uri = uri
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case file
        case filename
        case inputStream
        case _open = "open"
        case readable
        case uri
        case url
    }

}
