//
// RoleActor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a user assigned to a project role. */

public struct RoleActor: Codable {

    public enum ModelType: String, Codable { 
        case groupRoleActor = "atlassian-group-role-actor"
        case userRoleActor = "atlassian-user-role-actor"
    }
    public var actorGroup: AllOfRoleActorActorGroup?
    public var actorUser: AllOfRoleActorActorUser?
    /** The avatar of the role actor. */
    public var avatarUrl: String?
    /** The display name of the role actor. For users, depending on the user’s privacy setting, this may return an alternative value for the user&#x27;s name. */
    public var displayName: String?
    /** The ID of the role actor. */
    public var _id: Int64?
    /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
    public var name: String?
    /** The type of role actor. */
    public var type: ModelType?

    public init(actorGroup: AllOfRoleActorActorGroup? = nil, actorUser: AllOfRoleActorActorUser? = nil, avatarUrl: String? = nil, displayName: String? = nil, _id: Int64? = nil, name: String? = nil, type: ModelType? = nil) {
        self.actorGroup = actorGroup
        self.actorUser = actorUser
        self.avatarUrl = avatarUrl
        self.displayName = displayName
        self._id = _id
        self.name = name
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case actorGroup
        case actorUser
        case avatarUrl
        case displayName
        case _id = "id"
        case name
        case type
    }

}
