//
// RuleConfiguration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A rule configuration. */

public struct RuleConfiguration {

    /** Whether the rule is disabled. */
    public var disabled: Bool?
    /** A tag used to filter rules in [Get workflow transition rule configurations](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflow-transition-rules/#api-rest-api-3-workflow-rule-config-get). */
    public var tag: String?
    /** Configuration of the rule, as it is stored by the Connect or the Forge app on the rule configuration page. */
    public var value: String

    public init(disabled: Bool? = nil, tag: String? = nil, value: String) {
        self.disabled = disabled
        self.tag = tag
        self.value = value
    }


}
