//
// ScreenScheme.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A screen scheme. */

public struct ScreenScheme: Codable {

    /** The description of the screen scheme. */
    public var _description: String?
    /** The ID of the screen scheme. */
    public var _id: Int64?
    /** Details of the issue type screen schemes associated with the screen scheme. */
    public var issueTypeScreenSchemes: AllOfScreenSchemeIssueTypeScreenSchemes?
    /** The name of the screen scheme. */
    public var name: String?
    /** The IDs of the screens for the screen types of the screen scheme. */
    public var screens: AllOfScreenSchemeScreens?

    public init(_description: String? = nil, _id: Int64? = nil, issueTypeScreenSchemes: AllOfScreenSchemeIssueTypeScreenSchemes? = nil, name: String? = nil, screens: AllOfScreenSchemeScreens? = nil) {
        self._description = _description
        self._id = _id
        self.issueTypeScreenSchemes = issueTypeScreenSchemes
        self.name = name
        self.screens = screens
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case _id = "id"
        case issueTypeScreenSchemes
        case name
        case screens
    }

}
