//
// SecuritySchemeMembersRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of issue security scheme level new members. */

public struct SecuritySchemeMembersRequest: Codable {

    /** The list of level members which should be added to the issue security scheme level. */
    public var members: [SecuritySchemeLevelMemberBean]?

    public init(members: [SecuritySchemeLevelMemberBean]? = nil) {
        self.members = members
    }


}
