//
// SecuritySchemeWithProjects.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about an issue security scheme. */

public struct SecuritySchemeWithProjects: Codable {




}
