//
// ServerInformation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the Jira instance. */

public struct ServerInformation {

    /** The base URL of the Jira instance. */
    public var baseUrl: String?
    /** The timestamp when the Jira version was built. */
    public var buildDate: Date?
    /** The build number of the Jira version. */
    public var buildNumber: Int?
    /** The type of server deployment. This is always returned as *Cloud*. */
    public var deploymentType: String?
    /** The display URL of the Jira instance. */
    public var displayUrl: String?
    /** The display URL of Confluence. */
    public var displayUrlConfluence: String?
    /** The display URL of the Servicedesk Help Center. */
    public var displayUrlServicedeskHelpCenter: String?
    /** Jira instance health check results. Deprecated and no longer returned. */
    public var healthChecks: [HealthCheckResult]?
    /** The unique identifier of the Jira version. */
    public var scmInfo: String?
    /** The time in Jira when this request was responded to. */
    public var serverTime: Date?
    public var serverTimeZone: ServerInformationServerTimeZone?
    /** The name of the Jira instance. */
    public var serverTitle: String?
    /** The version of Jira. */
    public var version: String?
    /** The major, minor, and revision version numbers of the Jira version. */
    public var versionNumbers: [Int]?

    public init(baseUrl: String? = nil, buildDate: Date? = nil, buildNumber: Int? = nil, deploymentType: String? = nil, displayUrl: String? = nil, displayUrlConfluence: String? = nil, displayUrlServicedeskHelpCenter: String? = nil, healthChecks: [HealthCheckResult]? = nil, scmInfo: String? = nil, serverTime: Date? = nil, serverTimeZone: ServerInformationServerTimeZone? = nil, serverTitle: String? = nil, version: String? = nil, versionNumbers: [Int]? = nil) {
        self.baseUrl = baseUrl
        self.buildDate = buildDate
        self.buildNumber = buildNumber
        self.deploymentType = deploymentType
        self.displayUrl = displayUrl
        self.displayUrlConfluence = displayUrlConfluence
        self.displayUrlServicedeskHelpCenter = displayUrlServicedeskHelpCenter
        self.healthChecks = healthChecks
        self.scmInfo = scmInfo
        self.serverTime = serverTime
        self.serverTimeZone = serverTimeZone
        self.serverTitle = serverTitle
        self.version = version
        self.versionNumbers = versionNumbers
    }


}
