//
// ServiceRegistryTier.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ServiceRegistryTier: Codable {

    /** tier description */
    public var _description: String?
    /** tier ID */
    public var _id: UUID?
    /** tier level */
    public var level: Int?
    /** tier name */
    public var name: String?
    /** name key of the tier */
    public var nameKey: String?

    public init(_description: String? = nil, _id: UUID? = nil, level: Int? = nil, name: String? = nil, nameKey: String? = nil) {
        self._description = _description
        self._id = _id
        self.level = level
        self.name = name
        self.nameKey = nameKey
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case _id = "id"
        case level
        case name
        case nameKey
    }

}
