//
// SetDefaultResolutionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The new default issue resolution. */

public struct SetDefaultResolutionRequest: Codable {

    /** The ID of the new default issue resolution. Must be an existing ID or null. Setting this to null erases the default resolution setting. */
    public var _id: String

    public init(_id: String) {
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
    }

}
