//
// SimpleApplicationPropertyBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SimpleApplicationPropertyBean: Codable {

    /** The ID of the application property. */
    public var _id: String?
    /** The new value. */
    public var value: String?

    public init(_id: String? = nil, value: String? = nil) {
        self._id = _id
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case value
    }

}
