//
// SimplifiedHierarchyLevel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SimplifiedHierarchyLevel {

    /** The ID of the level above this one in the hierarchy. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var aboveLevelId: Int64?
    /** The ID of the level below this one in the hierarchy. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var belowLevelId: Int64?
    /** The external UUID of the hierarchy level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var externalUuid: UUID?
    public var hierarchyLevelNumber: Int?
    /** The ID of the hierarchy level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var _id: Int64?
    /** The issue types available in this hierarchy level. */
    public var issueTypeIds: [Int64]?
    /** The level of this item in the hierarchy. */
    public var level: Int?
    /** The name of this hierarchy level. */
    public var name: String?
    /** The ID of the project configuration. This property is deprecated, see [Change oticen: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var projectConfigurationId: Int64?

    public init(aboveLevelId: Int64? = nil, belowLevelId: Int64? = nil, externalUuid: UUID? = nil, hierarchyLevelNumber: Int? = nil, _id: Int64? = nil, issueTypeIds: [Int64]? = nil, level: Int? = nil, name: String? = nil, projectConfigurationId: Int64? = nil) {
        self.aboveLevelId = aboveLevelId
        self.belowLevelId = belowLevelId
        self.externalUuid = externalUuid
        self.hierarchyLevelNumber = hierarchyLevelNumber
        self._id = _id
        self.issueTypeIds = issueTypeIds
        self.level = level
        self.name = name
        self.projectConfigurationId = projectConfigurationId
    }

    public enum CodingKeys: String, CodingKey { 
        case aboveLevelId
        case belowLevelId
        case externalUuid
        case hierarchyLevelNumber
        case _id = "id"
        case issueTypeIds
        case level
        case name
        case projectConfigurationId
    }

}
