//
// SimpleListWrapperApplicationRole.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SimpleListWrapperApplicationRole: Codable {

    public var callback: ListWrapperCallbackApplicationRole?
    public var items: [ApplicationRole]?
    public var maxResults: Int?
    public var pagingCallback: ListWrapperCallbackApplicationRole?
    public var size: Int?

    public init(callback: ListWrapperCallbackApplicationRole? = nil, items: [ApplicationRole]? = nil, maxResults: Int? = nil, pagingCallback: ListWrapperCallbackApplicationRole? = nil, size: Int? = nil) {
        self.callback = callback
        self.items = items
        self.maxResults = maxResults
        self.pagingCallback = pagingCallback
        self.size = size
    }

    public enum CodingKeys: String, CodingKey { 
        case callback
        case items
        case maxResults = "max-results"
        case pagingCallback
        case size
    }

}
