//
// SoftwareNavigationInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SoftwareNavigationInfo {

    public var boardId: Int64?
    public var boardName: String?
    public var simpleBoard: Bool?
    public var totalBoardsInProject: Int64?

    public init(boardId: Int64? = nil, boardName: String? = nil, simpleBoard: Bool? = nil, totalBoardsInProject: Int64? = nil) {
        self.boardId = boardId
        self.boardName = boardName
        self.simpleBoard = simpleBoard
        self.totalBoardsInProject = totalBoardsInProject
    }


}
