//
// StatusCategory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A status category. */

public struct StatusCategory: Codable {




}
