//
// StatusReferenceAndPort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The status reference and port that a transition is connected to. */

public struct StatusReferenceAndPort: Codable {

    /** The port this transition uses to connect to this status. */
    public var port: Int?
    /** The reference of this status. */
    public var statusReference: String

    public init(port: Int? = nil, statusReference: String) {
        self.port = port
        self.statusReference = statusReference
    }


}
