//
// SuggestedIssue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An issue suggested for use in the issue picker auto-completion. */

public struct SuggestedIssue: Codable {

    /** The ID of the issue. */
    public var _id: Int64?
    /** The URL of the issue type&#x27;s avatar. */
    public var img: String?
    /** The key of the issue. */
    public var key: String?
    /** The key of the issue in HTML format. */
    public var keyHtml: String?
    /** The phrase containing the query string in HTML format, with the string highlighted with HTML bold tags. */
    public var summary: String?
    /** The phrase containing the query string, as plain text. */
    public var summaryText: String?

    public init(_id: Int64? = nil, img: String? = nil, key: String? = nil, keyHtml: String? = nil, summary: String? = nil, summaryText: String? = nil) {
        self._id = _id
        self.img = img
        self.key = key
        self.keyHtml = keyHtml
        self.summary = summary
        self.summaryText = summaryText
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case img
        case key
        case keyHtml
        case summary
        case summaryText
    }

}
