//
// TransitionScreenDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The details of a transition screen. */

public struct TransitionScreenDetails: Codable {

    /** The ID of the screen. */
    public var _id: String
    /** The name of the screen. */
    public var name: String?

    public init(_id: String, name: String? = nil) {
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
    }

}
