//
// Transition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a workflow transition. */

public struct Transition: Codable {

    public enum ModelType: String, Codable { 
        case global = "global"
        case initial = "initial"
        case directed = "directed"
    }
    /** The description of the transition. */
    public var _description: String
    /** The statuses the transition can start from. */
    public var from: [String]
    /** The ID of the transition. */
    public var _id: String
    /** The name of the transition. */
    public var name: String
    /** The properties of the transition. */
    public var properties: [String:Any]?
    public var rules: WorkflowRules?
    public var screen: TransitionScreenDetails?
    /** The status the transition goes to. */
    public var to: String
    /** The type of the transition. */
    public var type: ModelType

    public init(_description: String, from: [String], _id: String, name: String, properties: [String:Any]? = nil, rules: WorkflowRules? = nil, screen: TransitionScreenDetails? = nil, to: String, type: ModelType) {
        self._description = _description
        self.from = from
        self._id = _id
        self.name = name
        self.properties = properties
        self.rules = rules
        self.screen = screen
        self.to = to
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case from
        case _id = "id"
        case name
        case properties
        case rules
        case screen
        case to
        case type
    }

}
