//
// UpdateCustomFieldDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a custom field. */

public struct UpdateCustomFieldDetails: Codable {

    public enum SearcherKey: String, Codable { 
        case cascadingselectsearcher = "com.atlassian.jira.plugin.system.customfieldtypes:cascadingselectsearcher"
        case daterange = "com.atlassian.jira.plugin.system.customfieldtypes:daterange"
        case datetimerange = "com.atlassian.jira.plugin.system.customfieldtypes:datetimerange"
        case exactnumber = "com.atlassian.jira.plugin.system.customfieldtypes:exactnumber"
        case exacttextsearcher = "com.atlassian.jira.plugin.system.customfieldtypes:exacttextsearcher"
        case grouppickersearcher = "com.atlassian.jira.plugin.system.customfieldtypes:grouppickersearcher"
        case labelsearcher = "com.atlassian.jira.plugin.system.customfieldtypes:labelsearcher"
        case multiselectsearcher = "com.atlassian.jira.plugin.system.customfieldtypes:multiselectsearcher"
        case numberrange = "com.atlassian.jira.plugin.system.customfieldtypes:numberrange"
        case projectsearcher = "com.atlassian.jira.plugin.system.customfieldtypes:projectsearcher"
        case textsearcher = "com.atlassian.jira.plugin.system.customfieldtypes:textsearcher"
        case userpickergroupsearcher = "com.atlassian.jira.plugin.system.customfieldtypes:userpickergroupsearcher"
        case versionsearcher = "com.atlassian.jira.plugin.system.customfieldtypes:versionsearcher"
    }
    /** The description of the custom field. The maximum length is 40000 characters. */
    public var _description: String?
    /** The name of the custom field. It doesn&#x27;t have to be unique. The maximum length is 255 characters. */
    public var name: String?
    /** The searcher that defines the way the field is searched in Jira. It can be set to &#x60;null&#x60;, otherwise you must specify the valid searcher for the field type, as listed below (abbreviated values shown):   *  &#x60;cascadingselect&#x60;: &#x60;cascadingselectsearcher&#x60;  *  &#x60;datepicker&#x60;: &#x60;daterange&#x60;  *  &#x60;datetime&#x60;: &#x60;datetimerange&#x60;  *  &#x60;float&#x60;: &#x60;exactnumber&#x60; or &#x60;numberrange&#x60;  *  &#x60;grouppicker&#x60;: &#x60;grouppickersearcher&#x60;  *  &#x60;importid&#x60;: &#x60;exactnumber&#x60; or &#x60;numberrange&#x60;  *  &#x60;labels&#x60;: &#x60;labelsearcher&#x60;  *  &#x60;multicheckboxes&#x60;: &#x60;multiselectsearcher&#x60;  *  &#x60;multigrouppicker&#x60;: &#x60;multiselectsearcher&#x60;  *  &#x60;multiselect&#x60;: &#x60;multiselectsearcher&#x60;  *  &#x60;multiuserpicker&#x60;: &#x60;userpickergroupsearcher&#x60;  *  &#x60;multiversion&#x60;: &#x60;versionsearcher&#x60;  *  &#x60;project&#x60;: &#x60;projectsearcher&#x60;  *  &#x60;radiobuttons&#x60;: &#x60;multiselectsearcher&#x60;  *  &#x60;readonlyfield&#x60;: &#x60;textsearcher&#x60;  *  &#x60;select&#x60;: &#x60;multiselectsearcher&#x60;  *  &#x60;textarea&#x60;: &#x60;textsearcher&#x60;  *  &#x60;textfield&#x60;: &#x60;textsearcher&#x60;  *  &#x60;url&#x60;: &#x60;exacttextsearcher&#x60;  *  &#x60;userpicker&#x60;: &#x60;userpickergroupsearcher&#x60;  *  &#x60;version&#x60;: &#x60;versionsearcher&#x60; */
    public var searcherKey: SearcherKey?

    public init(_description: String? = nil, name: String? = nil, searcherKey: SearcherKey? = nil) {
        self._description = _description
        self.name = name
        self.searcherKey = searcherKey
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case name
        case searcherKey
    }

}
