//
// UpdateIssueSecuritySchemeRequestBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateIssueSecuritySchemeRequestBean: Codable {

    /** The description of the security scheme scheme. */
    public var _description: String?
    /** The name of the security scheme scheme. Must be unique. */
    public var name: String?

    public init(_description: String? = nil, name: String? = nil) {
        self._description = _description
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case name
    }

}
