//
// UpdatePrioritySchemeResponseBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the updated priority scheme. */

public struct UpdatePrioritySchemeResponseBean: Codable {




}
