//
// UpdateIssueSecurityLevelDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of issue security scheme level. */

public struct UpdateIssueSecurityLevelDetails: Codable {




}
