//
// UpdateDefaultScreenScheme.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The ID of a screen scheme. */

public struct UpdateDefaultScreenScheme: Codable {

    /** The ID of the screen scheme. */
    public var screenSchemeId: String

    public init(screenSchemeId: String) {
        self.screenSchemeId = screenSchemeId
    }


}
