//
// UpdateProjectsInSchemeRequestBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Update projects in a scheme */

public struct UpdateProjectsInSchemeRequestBean: Codable {




}
