//
// UserContextVariable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A [user](https://developer.atlassian.com/cloud/jira/platform/jira-expressions-type-reference#user) specified as an Atlassian account ID. */

public struct UserContextVariable: Codable {

    /** The account ID of the user. */
    public var accountId: String
    /** Type of custom context variable. */
    public var type: String

    public init(accountId: String, type: String) {
        self.accountId = accountId
        self.type = type
    }


}
