//
// UserPermission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a permission and its availability to a user. */

public struct UserPermission: Codable {




}
