//
// ValueOperand.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An operand that is a user-provided value. */

public struct ValueOperand {

    /** Encoded value, which can be used directly in a JQL query. */
    public var encodedValue: String?
    /** The operand value. */
    public var value: String

    public init(encodedValue: String? = nil, value: String) {
        self.encodedValue = encodedValue
        self.value = value
    }


}
