//
// VersionApprover.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains details about a version approver. */

public struct VersionApprover {




}
