//
// VersionRelatedWork.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Associated related work to a version */

public struct VersionRelatedWork: Codable {

    /** The category of the related work */
    public var category: String
    /** The ID of the issue associated with the related work (if there is one). Cannot be updated via the Rest API. */
    public var issueId: Int64?
    /** The id of the related work. For the native release note related work item, this will be null, and Rest API does not support updating it. */
    public var relatedWorkId: String?
    /** The title of the related work */
    public var title: String?
    /** The URL of the related work. Will be null for the native release note related work item, but is otherwise required. */
    public var url: String?

    public init(category: String, issueId: Int64? = nil, relatedWorkId: String? = nil, title: String? = nil, url: String? = nil) {
        self.category = category
        self.issueId = issueId
        self.relatedWorkId = relatedWorkId
        self.title = title
        self.url = url
    }


}
