//
// VersionIssuesStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Counts of the number of issues in various statuses. */

public struct VersionIssuesStatus {




}
