//
// VersionMoveBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VersionMoveBean: Codable {

    public enum Position: String, Codable { 
        case earlier = "Earlier"
        case later = "Later"
        case first = "First"
        case last = "Last"
    }
    /** The URL (self link) of the version after which to place the moved version. Cannot be used with &#x60;position&#x60;. */
    public var after: String?
    /** An absolute position in which to place the moved version. Cannot be used with &#x60;after&#x60;. */
    public var position: Position?

    public init(after: String? = nil, position: Position? = nil) {
        self.after = after
        self.position = position
    }


}
