//
// WorkflowTransitionRules.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A workflow with transition rules. */

public struct WorkflowTransitionRules: Codable {

    /** The list of conditions within the workflow. */
    public var conditions: [AppWorkflowTransitionRule]?
    /** The list of post functions within the workflow. */
    public var postFunctions: [AppWorkflowTransitionRule]?
    /** The list of validators within the workflow. */
    public var validators: [AppWorkflowTransitionRule]?
    public var workflowId: WorkflowId

    public init(conditions: [AppWorkflowTransitionRule]? = nil, postFunctions: [AppWorkflowTransitionRule]? = nil, validators: [AppWorkflowTransitionRule]? = nil, workflowId: WorkflowId) {
        self.conditions = conditions
        self.postFunctions = postFunctions
        self.validators = validators
        self.workflowId = workflowId
    }


}
