//
// WorkflowSchemeAssociations.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A workflow scheme along with a list of projects that use it. */

public struct WorkflowSchemeAssociations: Codable {

    /** The list of projects that use the workflow scheme. */
    public var projectIds: [String]
    /** The workflow scheme. */
    public var workflowScheme: AllOfWorkflowSchemeAssociationsWorkflowScheme

    public init(projectIds: [String], workflowScheme: AllOfWorkflowSchemeAssociationsWorkflowScheme) {
        self.projectIds = projectIds
        self.workflowScheme = workflowScheme
    }


}
