//
// WorkManagementNavigationInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WorkManagementNavigationInfo: Codable {

    public var boardName: String?

    public init(boardName: String? = nil) {
        self.boardName = boardName
    }


}
