//
// WorkflowCreateValidateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WorkflowCreateValidateRequest: Codable {

    public var payload: WorkflowCreateRequest
    public var validationOptions: ValidationOptionsForCreate?

    public init(payload: WorkflowCreateRequest, validationOptions: ValidationOptionsForCreate? = nil) {
        self.payload = payload
        self.validationOptions = validationOptions
    }


}
