//
// WorkflowRulesSearchDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of workflow transition rules. */

public struct WorkflowRulesSearchDetails: Codable {

    /** List of workflow rule IDs that do not belong to the workflow or can not be found. */
    public var invalidRules: [UUID]?
    /** List of valid workflow transition rules. */
    public var validRules: [WorkflowTransitionRules]?
    /** The workflow ID. */
    public var workflowEntityId: UUID?

    public init(invalidRules: [UUID]? = nil, validRules: [WorkflowTransitionRules]? = nil, workflowEntityId: UUID? = nil) {
        self.invalidRules = invalidRules
        self.validRules = validRules
        self.workflowEntityId = workflowEntityId
    }


}
