//
// WorkflowTrigger.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The trigger configuration associated with a workflow. */

public struct WorkflowTrigger: Codable {

    /** The ID of the trigger. */
    public var _id: String?
    /** The parameters of the trigger. */
    public var parameters: [String:String]
    /** The rule key of the trigger. */
    public var ruleKey: String

    public init(_id: String? = nil, parameters: [String:String], ruleKey: String) {
        self._id = _id
        self.parameters = parameters
        self.ruleKey = ruleKey
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case parameters
        case ruleKey
    }

}
