//
// WorkflowCondition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The workflow transition rule conditions tree. */

public struct WorkflowCondition: Codable {




}
