//
// PrioritySchemeWithPaginatedPrioritiesAndProjects.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A priority scheme with paginated priorities and projects. */

public struct PrioritySchemeWithPaginatedPrioritiesAndProjects {




}
