//
// PrioritySchemeId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The ID of a priority scheme. */

public struct PrioritySchemeId {

    /** The ID of the priority scheme. */
    public var _id: String?
    /** The in-progress issue migration task. */
    public var task: AllOfPrioritySchemeIdTask?

    public init(_id: String? = nil, task: AllOfPrioritySchemeIdTask? = nil) {
        self._id = _id
        self.task = task
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case task
    }

}
