//
// IssueTypeCreateBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IssueTypeCreateBean {

    public enum ModelType: String, Codable { 
        case subtask = "subtask"
        case standard = "standard"
    }
    /** The description of the issue type. */
    public var _description: String?
    /** The hierarchy level of the issue type. Use:   *  &#x60;-1&#x60; for Subtask.  *  &#x60;0&#x60; for Base.  Defaults to &#x60;0&#x60;. */
    public var hierarchyLevel: Int?
    /** The unique name for the issue type. The maximum length is 60 characters. */
    public var name: String

    public init(_description: String? = nil, hierarchyLevel: Int? = nil, name: String) {
        self._description = _description
        self.hierarchyLevel = hierarchyLevel
        self.name = name
    }

    internal init(client: Components.Schemas.IssueTypeCreateBean)
}
