//
// WorkflowTransitionRulesUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a workflow configuration update request. */

public struct WorkflowTransitionRulesUpdate {

    /** The list of workflows with transition rules to update. */
    public var workflows: [WorkflowTransitionRules]

    public init(workflows: [WorkflowTransitionRules]) {
        self.workflows = workflows
    }


}
