//
// WorkflowTransitionProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the server Jira is running on. */

public struct WorkflowTransitionProperty {




}
