//
// IssueContextVariable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An [issue](https://developer.atlassian.com/cloud/jira/platform/jira-expressions-type-reference#issue) specified by ID or key. All the fields of the issue object are available in the Jira expression. */

public struct IssueContextVariable {

    /** The issue ID. */
    public var _id: Int64?
    /** The issue key. */
    public var key: String?
    /** Type of custom context variable. */
    public var type: String

    public init(_id: Int64? = nil, key: String? = nil, type: String) {
        self._id = _id
        self.key = key
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case key
        case type
    }

}
