//
// IssueUpdateMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of editable field details. */

public struct IssueUpdateMetadata {

    public let fields: [String:FieldMetadata]?

    public init(fields: [String:FieldMetadata]? = nil) {
        self.fields = fields
    }

    internal init(client: Components.Schemas.IssueUpdateMetadata?) {
        self.fields = client?.fields?.additionalProperties.mapValues{ FieldMetadata(client: $0)}
    }
}
