//
// IssueSecuritySchemeToProjectMapping.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about an project using security scheme mapping. */

public struct IssueSecuritySchemeToProjectMapping {




}
