//
// TransitionScreenDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The details of a transition screen. */

public struct TransitionScreenDetails {

    /** The ID of the screen. */
    public let id: String
    /** The name of the screen. */
    public let name: String?

    public init(id: String, name: String? = nil) {
        self.id = id
        self.name = name
    }

    internal init(client: Components.Schemas.TransitionScreenDetails?) {
        self.id = client!.id
        self.name = client?.name
    }
}
