//
// AllOfGroupUsers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A paginated list of the users that are members of the group. A maximum of 50 users is returned in the list, to access additional users append &#x60;[start-index:end-index]&#x60; to the expand request. For example, to access the next 50 users, use&#x60;?expand&#x3D;users[51:100]&#x60;. */

public struct AllOfGroupUsers {

    /** The index of the last item returned on the page. */
    public var endIndex: Int?
    /** The list of items. */
    public var items: [User]?
    /** The maximum number of results that could be on the page. */
    public var maxResults: Int?
    /** The number of items on the page. */
    public var size: Int?
    /** The index of the first item returned on the page. */
    public var startIndex: Int?

    public init(endIndex: Int? = nil, items: [User]? = nil, maxResults: Int? = nil, size: Int? = nil, startIndex: Int? = nil) {
        self.endIndex = endIndex
        self.items = items
        self.maxResults = maxResults
        self.size = size
        self.startIndex = startIndex
    }
    
}
