//
// Group.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Group {

    /** Expand options that include additional group details in the response. */
    public var expand: String?
    /** The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*. */
    public var groupId: String?
    /** The name of group. */
    public var name: String?
    /** The URL for these group details. */
    public var _self: String?
    /** A paginated list of the users that are members of the group. A maximum of 50 users is returned in the list, to access additional users append &#x60;[start-index:end-index]&#x60; to the expand request. For example, to access the next 50 users, use&#x60;?expand&#x3D;users[51:100]&#x60;. */
    public var users: AllOfGroupUsers?

    public init(expand: String? = nil, groupId: String? = nil, name: String? = nil, _self: String? = nil, users: AllOfGroupUsers? = nil) {
        self.expand = expand
        self.groupId = groupId
        self.name = name
        self._self = _self
        self.users = users
    }

    public enum CodingKeys: String, CodingKey { 
        case expand
        case groupId
        case name
        case _self = "self"
        case users
    }

}
