//
// ProjectInsight.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Additional details about a project. */

public struct ProjectInsight {

    /** The last issue update time. */
    public let lastIssueUpdateTime: Date?
    /** Total issue count. */
    public let totalIssueCount: Int64?

    public init(lastIssueUpdateTime: Date? = nil, totalIssueCount: Int64? = nil) {
        self.lastIssueUpdateTime = lastIssueUpdateTime
        self.totalIssueCount = totalIssueCount
    }

    internal init(client: Components.Schemas.ProjectInsight?) {
        self.lastIssueUpdateTime = client?.lastIssueUpdateTime
        self.totalIssueCount = client?.totalIssueCount
    }
}
