//
// ProjectIssueTypes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Use the optional &#x60;workflows.usages&#x60; expand to get additional information about the projects and issue types associated with the requested workflows. */

public struct ProjectIssueTypes {

    /** IDs of the issue types */
    public var issueTypes: [String]?
    public var project: ProjectId?

    public init(issueTypes: [String]? = nil, project: ProjectId? = nil) {
        self.issueTypes = issueTypes
        self.project = project
    }


}
