//
// ProjectDataPolicy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about data policy. */

public struct ProjectDataPolicy {

    /** Whether the project contains any content inaccessible to the requesting application. */
    public var anyContentBlocked: Bool?

    public init(anyContentBlocked: Bool? = nil) {
        self.anyContentBlocked = anyContentBlocked
    }


}
