//
// SimplifiedHierarchyLevel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SimplifiedHierarchyLevel {

    /** The ID of the level above this one in the hierarchy. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var aboveLevelId: Int64?
    /** The ID of the level below this one in the hierarchy. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var belowLevelId: Int64?
    /** The external UUID of the hierarchy level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var externalUuid: String?
    public var hierarchyLevelNumber: Int32?
    /** The ID of the hierarchy level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var id: Int64?
    /** The issue types available in this hierarchy level. */
    public var issueTypeIds: [Int64]?
    /** The level of this item in the hierarchy. */
    public var level: Int32?
    /** The name of this hierarchy level. */
    public var name: String?
    /** The ID of the project configuration. This property is deprecated, see [Change oticen: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/). */
    public var projectConfigurationId: Int64?

    public init(aboveLevelId: Int64? = nil, belowLevelId: Int64? = nil, externalUuid: String? = nil, hierarchyLevelNumber: Int32? = nil, id: Int64? = nil, issueTypeIds: [Int64]? = nil, level: Int32? = nil, name: String? = nil, projectConfigurationId: Int64? = nil) {
        self.aboveLevelId = aboveLevelId
        self.belowLevelId = belowLevelId
        self.externalUuid = externalUuid
        self.hierarchyLevelNumber = hierarchyLevelNumber
        self.id = id
        self.issueTypeIds = issueTypeIds
        self.level = level
        self.name = name
        self.projectConfigurationId = projectConfigurationId
    }

    internal init(client: Components.Schemas.SimplifiedHierarchyLevel?) {
        self.aboveLevelId = client?.aboveLevelId
        self.belowLevelId = client?.belowLevelId
        self.externalUuid = client?.externalUuid
        self.hierarchyLevelNumber = client?.hierarchyLevelNumber
        self.id = client?.id
        self.issueTypeIds = client?.issueTypeIds
        self.level = client?.level
        self.name = client?.name
        self.projectConfigurationId = client?.projectConfigurationId
    }

}
