//
// Changelog.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A log of changes made to issue fields. Changelogs related to workflow associations are currently being deprecated. */

public struct Changelog {

    /** The user who made the change. */
    public var author: User?
    /** The date on which the change took place. */
    public var created: Date?
    /** The history metadata associated with the changed. */
    public var historyMetadata: HistoryMetadata?
    /** The ID of the changelog. */
    public var id: String?
    /** The list of items changed. */
    public var items: [ChangeDetails]?

    public init(author: User? = nil, created: Date? = nil, historyMetadata: HistoryMetadata? = nil, _id: String? = nil, items: [ChangeDetails]? = nil) {
        self.author = author
        self.created = created
        self.historyMetadata = historyMetadata
        self.id = _id
        self.items = items
    }
    
    internal init(client: Components.Schemas.Changelog?) {
        self.historyMetadata = HistoryMetadata(client: client?.historyMetadata?.value1)
        self.created = client?.created
        self.id = client?.id
        self.items = client?.items?.map{ ChangeDetails(client: $0) }
    }
}
