//
// PageOfChangelogs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A page of changelogs. */

public struct PageOfChangelogs {

    /** The list of changelogs. */
    public let histories: [Changelog]?
    /** The maximum number of results that could be on the page. */
    public let maxResults: Int32?
    /** The index of the first item returned on the page. */
    public let startAt: Int32?
    /** The number of results on the page. */
    public let total: Int32?

    public init(histories: [Changelog]? = nil, maxResults: Int32? = nil, startAt: Int32? = nil, total: Int32? = nil) {
        self.histories = histories
        self.maxResults = maxResults
        self.startAt = startAt
        self.total = total
    }

    internal init(client: Components.Schemas.PageOfChangelogs?) {
        self.histories = client?.histories?.map{ Changelog(client: $0) }
        self.maxResults = client?.maxResults
        self.startAt = client?.startAt
        self.total = client?.total
    }


}
