//
// PrioritySchemeChangesWithoutMappings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PrioritySchemeChangesWithoutMappings {

    /** Affected entity ids. */
    public var ids: [Int64]

    public init(ids: [Int64]) {
        self.ids = ids
    }


}
