//
// UserAvatarUrls.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The avatars of the user. */

public struct UserAvatarUrls {

    /** The URL of the item&#x27;s 16x16 pixel avatar. */
    public let _16x16: String?
    /** The URL of the item&#x27;s 24x24 pixel avatar. */
    public let _24x24: String?
    /** The URL of the item&#x27;s 32x32 pixel avatar. */
    public let _32x32: String?
    /** The URL of the item&#x27;s 48x48 pixel avatar. */
    public let _48x48: String?

    public init(_16x16: String? = nil, _24x24: String? = nil, _32x32: String? = nil, _48x48: String? = nil) {
        self._16x16 = _16x16
        self._24x24 = _24x24
        self._32x32 = _32x32
        self._48x48 = _48x48
    }
    
    internal init(client: Components.Schemas.AvatarUrlsBean?) {
        self._16x16 = client?._16x16
        self._24x24 = client?._24x24
        self._32x32 = client?._32x32
        self._48x48 = client?._48x48
    }
}
