//
// AllOfBulkEditShareableEntityRequestChangeOwnerDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The details of change owner action. */

public struct AllOfBulkEditShareableEntityRequestChangeOwnerDetails {

    /** Whether the name is fixed automatically if it&#x27;s duplicated after changing owner. */
    public var autofixName: Bool
    /** The account id of the new owner. */
    public var newOwner: String

    public init(autofixName: Bool, newOwner: String) {
        self.autofixName = autofixName
        self.newOwner = newOwner
    }


}
