//
// AllOfJiraExpressionsComplexityBeanSteps.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The number of steps it took to evaluate the expression, where a step is a high-level operation performed by the expression. A step is an operation such as arithmetic, accessing a property, accessing a context variable, or calling a function. */

public struct AllOfJiraExpressionsComplexityBeanSteps {

    /** The maximum allowed complexity. The evaluation will fail if this value is exceeded. */
    public var limit: Int
    /** The complexity value of the current expression. */
    public var value: Int

    public init(limit: Int, value: Int) {
        self.limit = limit
        self.value = value
    }


}
