//
// AllOfTaskProgressBeanRemoveOptionFromIssuesResultResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The result of the task execution. */

public struct AllOfTaskProgressBeanRemoveOptionFromIssuesResultResult {

    /** A collection of errors related to unchanged issues. The collection size is limited, which means not all errors may be returned. */
    public var errors: Any?
    /** The IDs of the modified issues. */
    public var modifiedIssues: [Int64]?
    /** The IDs of the unchanged issues, those issues where errors prevent modification. */
    public var unmodifiedIssues: [Int64]?

    public init(errors: Any? = nil, modifiedIssues: [Int64]? = nil, unmodifiedIssues: [Int64]? = nil) {
        self.errors = errors
        self.modifiedIssues = modifiedIssues
        self.unmodifiedIssues = unmodifiedIssues
    }


}
