//
// AllOfScreenWithTabTab.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The tab for the screen. */

public struct AllOfScreenWithTabTab {

    /** The ID of the screen tab. */
    public var _id: Int64?
    /** The name of the screen tab. The maximum length is 255 characters. */
    public var name: String

    public init(_id: Int64? = nil, name: String) {
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
    }

}
