//
// AllOfJiraExpressionEvalContextBeanProject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The project that is available under the &#x60;project&#x60; variable when evaluating the expression. */

public struct AllOfJiraExpressionEvalContextBeanProject {

    /** The ID of the referenced item. */
    public var _id: Int64?
    /** The key of the referenced item. */
    public var key: String?

    public init(_id: Int64? = nil, key: String? = nil) {
        self._id = _id
        self.key = key
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case key
    }

}
