//
// AllOfScreenSchemeScreens.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The IDs of the screens for the screen types of the screen scheme. */

public struct AllOfScreenSchemeScreens {

    /** The ID of the create screen. */
    public var create: Int64?
    /** The ID of the default screen. Required when creating a screen scheme. */
    public var _default: Int64
    /** The ID of the edit screen. */
    public var edit: Int64?
    /** The ID of the view screen. */
    public var view: Int64?

    public init(create: Int64? = nil, _default: Int64, edit: Int64? = nil, view: Int64? = nil) {
        self.create = create
        self._default = _default
        self.edit = edit
        self.view = view
    }

    public enum CodingKeys: String, CodingKey { 
        case create
        case _default = "default"
        case edit
        case view
    }

}
