//
// AllOfBulkIssuePropertyUpdateRequestFilter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The bulk operation filter. */

public struct AllOfBulkIssuePropertyUpdateRequestFilter {

    /** The value of properties to perform the bulk operation on. */
    public var currentValue: Any?
    /** List of issues to perform the bulk operation on. */
    public var entityIds: [Int64]?
    /** Whether the bulk operation occurs only when the property is present on or absent from an issue. */
    public var hasProperty: Bool?

    public init(currentValue: Any? = nil, entityIds: [Int64]? = nil, hasProperty: Bool? = nil) {
        self.currentValue = currentValue
        self.entityIds = entityIds
        self.hasProperty = hasProperty
    }


}
