//
// AllOfRoleActorActorGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AllOfRoleActorActorGroup {

    /** The display name of the group. */
    public var displayName: String?
    /** The ID of the group. */
    public var groupId: String?
    /** The name of the group. As a group&#x27;s name can change, use of &#x60;groupId&#x60; is recommended to identify the group. */
    public var name: String?

    public init(displayName: String? = nil, groupId: String? = nil, name: String? = nil) {
        self.displayName = displayName
        self.groupId = groupId
        self.name = name
    }


}
