//
// AssociatedItemBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of an item associated with the changed record. */

public struct AssociatedItemBean {

    /** The ID of the associated record. */
    public var _id: String?
    /** The name of the associated record. */
    public var name: String?
    /** The ID of the associated parent record. */
    public var parentId: String?
    /** The name of the associated parent record. */
    public var parentName: String?
    /** The type of the associated record. */
    public var typeName: String?

    public init(_id: String? = nil, name: String? = nil, parentId: String? = nil, parentName: String? = nil, typeName: String? = nil) {
        self._id = _id
        self.name = name
        self.parentId = parentId
        self.parentName = parentName
        self.typeName = typeName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case parentId
        case parentName
        case typeName
    }

}
