//
// AvailableWorkflowTriggers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The trigger rules available. */

public struct AvailableWorkflowTriggers {

    /** The list of available trigger types. */
    public var availableTypes: [AvailableWorkflowTriggerTypes]
    /** The rule key of the rule. */
    public var ruleKey: String

    public init(availableTypes: [AvailableWorkflowTriggerTypes], ruleKey: String) {
        self.availableTypes = availableTypes
        self.ruleKey = ruleKey
    }


}
