//
// BulkIssueResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of requested issues &amp; fields. */

public struct BulkIssueResults {

    /** When Jira can&#x27;t return an issue enumerated in a request due to a retriable error or payload constraint, we&#x27;ll return the respective issue ID with a corresponding error message. This list is empty when there are no errors Issues which aren&#x27;t found or that the user doesn&#x27;t have permission to view won&#x27;t be returned in this list. */
    public var issueErrors: [IssueError]?
    /** The list of issues. */
    public var issues: [Issue]?

    public init(issueErrors: [IssueError]? = nil, issues: [Issue]? = nil) {
        self.issueErrors = issueErrors
        self.issues = issues
    }


}
