//
// BulkPermissionGrants.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of global and project permissions granted to the user. */

public struct BulkPermissionGrants {

    /** List of permissions granted to the user. */
    public var globalPermissions: [String]
    /** List of project permissions and the projects and issues those permissions provide access to. */
    public var projectPermissions: [BulkProjectPermissionGrants]

    public init(globalPermissions: [String], projectPermissions: [BulkProjectPermissionGrants]) {
        self.globalPermissions = globalPermissions
        self.projectPermissions = projectPermissions
    }


}
