//
// BulkCustomFieldOptionUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the options to update for a custom field. */

public struct BulkCustomFieldOptionUpdateRequest {

    /** Details of the options to update. */
    public var options: [CustomFieldOptionUpdate]?

    public init(options: [CustomFieldOptionUpdate]? = nil) {
        self.options = options
    }


}
