//
// BulkPermissionsRequestBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of global permissions to look up and project permissions with associated projects and issues to look up. */

public struct BulkPermissionsRequestBean {

    /** The account ID of a user. */
    public var accountId: String?
    /** Global permissions to look up. */
    public var globalPermissions: [String]?
    /** Project permissions with associated projects and issues to look up. */
    public var projectPermissions: [BulkProjectPermissions]?

    public init(accountId: String? = nil, globalPermissions: [String]? = nil, projectPermissions: [BulkProjectPermissions]? = nil) {
        self.accountId = accountId
        self.globalPermissions = globalPermissions
        self.projectPermissions = projectPermissions
    }


}
