//
// ChangedWorklogs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List of changed worklogs. */

public struct ChangedWorklogs {

    public var lastPage: Bool?
    /** The URL of the next list of changed worklogs. */
    public var nextPage: String?
    /** The URL of this changed worklogs list. */
    public var _self: String?
    /** The datetime of the first worklog item in the list. */
    public var since: Int64?
    /** The datetime of the last worklog item in the list. */
    public var until: Int64?
    /** Changed worklog list. */
    public var values: [ChangedWorklog]?

    public init(lastPage: Bool? = nil, nextPage: String? = nil, _self: String? = nil, since: Int64? = nil, until: Int64? = nil, values: [ChangedWorklog]? = nil) {
        self.lastPage = lastPage
        self.nextPage = nextPage
        self._self = _self
        self.since = since
        self.until = until
        self.values = values
    }

}
