//
// ConfigurationsListParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List of custom fields identifiers which will be used to filter configurations */

public struct ConfigurationsListParameters {

    /** List of IDs or keys of the custom fields. It can be a mix of IDs and keys in the same query. */
    public var fieldIdsOrKeys: [String]

    public init(fieldIdsOrKeys: [String]) {
        self.fieldIdsOrKeys = fieldIdsOrKeys
    }


}
