//
// CreateProjectDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the project. */

public struct CreateProjectDetails {

    public enum AssigneeType: String, Codable { 
        case projectLead = "PROJECT_LEAD"
        case unassigned = "UNASSIGNED"
    }
    public enum ProjectTemplateKey: String, Codable { 
        case pyxisGreenhopperJiraGhSimplifiedAgilityKanban = "com.pyxis.greenhopper.jira:gh-simplified-agility-kanban"
        case pyxisGreenhopperJiraGhSimplifiedAgilityScrum = "com.pyxis.greenhopper.jira:gh-simplified-agility-scrum"
        case pyxisGreenhopperJiraGhSimplifiedBasic = "com.pyxis.greenhopper.jira:gh-simplified-basic"
        case pyxisGreenhopperJiraGhSimplifiedKanbanClassic = "com.pyxis.greenhopper.jira:gh-simplified-kanban-classic"
        case pyxisGreenhopperJiraGhSimplifiedScrumClassic = "com.pyxis.greenhopper.jira:gh-simplified-scrum-classic"
        case pyxisGreenhopperJiraGhCrossTeamTemplate = "com.pyxis.greenhopper.jira:gh-cross-team-template"
        case pyxisGreenhopperJiraGhCrossTeamPlanningTemplate = "com.pyxis.greenhopper.jira:gh-cross-team-planning-template"
        case atlassianServicedeskSimplifiedItServiceManagement = "com.atlassian.servicedesk:simplified-it-service-management"
        case atlassianServicedeskSimplifiedItServiceManagementBasic = "com.atlassian.servicedesk:simplified-it-service-management-basic"
        case atlassianServicedeskSimplifiedGeneralServiceDesk = "com.atlassian.servicedesk:simplified-general-service-desk"
        case atlassianServicedeskSimplifiedGeneralServiceDeskIt = "com.atlassian.servicedesk:simplified-general-service-desk-it"
        case atlassianServicedeskSimplifiedGeneralServiceDeskBusiness = "com.atlassian.servicedesk:simplified-general-service-desk-business"
        case atlassianServicedeskSimplifiedInternalServiceDesk = "com.atlassian.servicedesk:simplified-internal-service-desk"
        case atlassianServicedeskSimplifiedExternalServiceDesk = "com.atlassian.servicedesk:simplified-external-service-desk"
        case atlassianServicedeskSimplifiedHrServiceDesk = "com.atlassian.servicedesk:simplified-hr-service-desk"
        case atlassianServicedeskSimplifiedFacilitiesServiceDesk = "com.atlassian.servicedesk:simplified-facilities-service-desk"
        case atlassianServicedeskSimplifiedLegalServiceDesk = "com.atlassian.servicedesk:simplified-legal-service-desk"
        case atlassianServicedeskSimplifiedMarketingServiceDesk = "com.atlassian.servicedesk:simplified-marketing-service-desk"
        case atlassianServicedeskSimplifiedFinanceServiceDesk = "com.atlassian.servicedesk:simplified-finance-service-desk"
        case atlassianServicedeskSimplifiedAnalyticsServiceDesk = "com.atlassian.servicedesk:simplified-analytics-service-desk"
        case atlassianServicedeskSimplifiedDesignServiceDesk = "com.atlassian.servicedesk:simplified-design-service-desk"
        case atlassianServicedeskSimplifiedSalesServiceDesk = "com.atlassian.servicedesk:simplified-sales-service-desk"
        case atlassianServicedeskSimplifiedHalpServiceDesk = "com.atlassian.servicedesk:simplified-halp-service-desk"
        case atlassianServicedeskSimplifiedBlankProjectIt = "com.atlassian.servicedesk:simplified-blank-project-it"
        case atlassianServicedeskSimplifiedBlankProjectBusiness = "com.atlassian.servicedesk:simplified-blank-project-business"
        case atlassianServicedeskNextGenItServiceDesk = "com.atlassian.servicedesk:next-gen-it-service-desk"
        case atlassianServicedeskNextGenHrServiceDesk = "com.atlassian.servicedesk:next-gen-hr-service-desk"
        case atlassianServicedeskNextGenLegalServiceDesk = "com.atlassian.servicedesk:next-gen-legal-service-desk"
        case atlassianServicedeskNextGenMarketingServiceDesk = "com.atlassian.servicedesk:next-gen-marketing-service-desk"
        case atlassianServicedeskNextGenFacilitiesServiceDesk = "com.atlassian.servicedesk:next-gen-facilities-service-desk"
        case atlassianServicedeskNextGenGeneralServiceDesk = "com.atlassian.servicedesk:next-gen-general-service-desk"
        case atlassianServicedeskNextGenGeneralItServiceDesk = "com.atlassian.servicedesk:next-gen-general-it-service-desk"
        case atlassianServicedeskNextGenGeneralBusinessServiceDesk = "com.atlassian.servicedesk:next-gen-general-business-service-desk"
        case atlassianServicedeskNextGenAnalyticsServiceDesk = "com.atlassian.servicedesk:next-gen-analytics-service-desk"
        case atlassianServicedeskNextGenFinanceServiceDesk = "com.atlassian.servicedesk:next-gen-finance-service-desk"
        case atlassianServicedeskNextGenDesignServiceDesk = "com.atlassian.servicedesk:next-gen-design-service-desk"
        case atlassianServicedeskNextGenSalesServiceDesk = "com.atlassian.servicedesk:next-gen-sales-service-desk"
        case atlassianJiraCoreProjectTemplatesJiraCoreSimplifiedContentManagement = "com.atlassian.jira-core-project-templates:jira-core-simplified-content-management"
        case atlassianJiraCoreProjectTemplatesJiraCoreSimplifiedDocumentApproval = "com.atlassian.jira-core-project-templates:jira-core-simplified-document-approval"
        case atlassianJiraCoreProjectTemplatesJiraCoreSimplifiedLeadTracking = "com.atlassian.jira-core-project-templates:jira-core-simplified-lead-tracking"
        case atlassianJiraCoreProjectTemplatesJiraCoreSimplifiedProcessControl = "com.atlassian.jira-core-project-templates:jira-core-simplified-process-control"
        case atlassianJiraCoreProjectTemplatesJiraCoreSimplifiedProcurement = "com.atlassian.jira-core-project-templates:jira-core-simplified-procurement"
        case atlassianJiraCoreProjectTemplatesJiraCoreSimplifiedProjectManagement = "com.atlassian.jira-core-project-templates:jira-core-simplified-project-management"
        case atlassianJiraCoreProjectTemplatesJiraCoreSimplifiedRecruitment = "com.atlassian.jira-core-project-templates:jira-core-simplified-recruitment"
        case atlassianJiraCoreProjectTemplatesJiraCoreSimplifiedTask = "com.atlassian.jira-core-project-templates:jira-core-simplified-task-"
    }
    public enum ProjectTypeKey: String, Codable { 
        case software = "software"
        case serviceDesk = "service_desk"
        case business = "business"
    }
    /** The default assignee when creating issues for this project. */
    public var assigneeType: AssigneeType?
    /** An integer value for the project&#x27;s avatar. */
    public var avatarId: Int64?
    /** The ID of the project&#x27;s category. A complete list of category IDs is found using the [Get all project categories](#api-rest-api-2-projectCategory-get) operation. */
    public var categoryId: Int64?
    /** A brief description of the project. */
    public var _description: String?
    /** The ID of the field configuration scheme for the project. Use the [Get all field configuration schemes](#api-rest-api-2-fieldconfigurationscheme-get) operation to get a list of field configuration scheme IDs. If you specify the field configuration scheme you cannot specify the project template key. */
    public var fieldConfigurationScheme: Int64?
    /** The ID of the issue security scheme for the project, which enables you to control who can and cannot view issues. Use the [Get issue security schemes](#api-rest-api-2-issuesecurityschemes-get) resource to get all issue security scheme IDs. */
    public var issueSecurityScheme: Int64?
    /** The ID of the issue type scheme for the project. Use the [Get all issue type schemes](#api-rest-api-2-issuetypescheme-get) operation to get a list of issue type scheme IDs. If you specify the issue type scheme you cannot specify the project template key. */
    public var issueTypeScheme: Int64?
    /** The ID of the issue type screen scheme for the project. Use the [Get all issue type screen schemes](#api-rest-api-2-issuetypescreenscheme-get) operation to get a list of issue type screen scheme IDs. If you specify the issue type screen scheme you cannot specify the project template key. */
    public var issueTypeScreenScheme: Int64?
    /** Project keys must be unique and start with an uppercase letter followed by one or more uppercase alphanumeric characters. The maximum length is 10 characters. */
    public var key: String
    /** This parameter is deprecated because of privacy changes. Use &#x60;leadAccountId&#x60; instead. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. The user name of the project lead. Either &#x60;lead&#x60; or &#x60;leadAccountId&#x60; must be set when creating a project. Cannot be provided with &#x60;leadAccountId&#x60;. */
    public var lead: String?
    /** The account ID of the project lead. Either &#x60;lead&#x60; or &#x60;leadAccountId&#x60; must be set when creating a project. Cannot be provided with &#x60;lead&#x60;. */
    public var leadAccountId: String?
    /** The name of the project. */
    public var name: String
    /** The ID of the notification scheme for the project. Use the [Get notification schemes](#api-rest-api-2-notificationscheme-get) resource to get a list of notification scheme IDs. */
    public var notificationScheme: Int64?
    /** The ID of the permission scheme for the project. Use the [Get all permission schemes](#api-rest-api-2-permissionscheme-get) resource to see a list of all permission scheme IDs. */
    public var permissionScheme: Int64?
    /** A predefined configuration for a project. The type of the &#x60;projectTemplateKey&#x60; must match with the type of the &#x60;projectTypeKey&#x60;. */
    public var projectTemplateKey: ProjectTemplateKey?
    /** The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes), which defines the application-specific feature set. If you don&#x27;t specify the project template you have to specify the project type. */
    public var projectTypeKey: ProjectTypeKey?
    /** A link to information about this project, such as project documentation */
    public var url: String?
    /** The ID of the workflow scheme for the project. Use the [Get all workflow schemes](#api-rest-api-2-workflowscheme-get) operation to get a list of workflow scheme IDs. If you specify the workflow scheme you cannot specify the project template key. */
    public var workflowScheme: Int64?

    public init(assigneeType: AssigneeType? = nil, avatarId: Int64? = nil, categoryId: Int64? = nil, _description: String? = nil, fieldConfigurationScheme: Int64? = nil, issueSecurityScheme: Int64? = nil, issueTypeScheme: Int64? = nil, issueTypeScreenScheme: Int64? = nil, key: String, lead: String? = nil, leadAccountId: String? = nil, name: String, notificationScheme: Int64? = nil, permissionScheme: Int64? = nil, projectTemplateKey: ProjectTemplateKey? = nil, projectTypeKey: ProjectTypeKey? = nil, url: String? = nil, workflowScheme: Int64? = nil) {
        self.assigneeType = assigneeType
        self.avatarId = avatarId
        self.categoryId = categoryId
        self._description = _description
        self.fieldConfigurationScheme = fieldConfigurationScheme
        self.issueSecurityScheme = issueSecurityScheme
        self.issueTypeScheme = issueTypeScheme
        self.issueTypeScreenScheme = issueTypeScreenScheme
        self.key = key
        self.lead = lead
        self.leadAccountId = leadAccountId
        self.name = name
        self.notificationScheme = notificationScheme
        self.permissionScheme = permissionScheme
        self.projectTemplateKey = projectTemplateKey
        self.projectTypeKey = projectTypeKey
        self.url = url
        self.workflowScheme = workflowScheme
    }

    public enum CodingKeys: String, CodingKey { 
        case assigneeType
        case avatarId
        case categoryId
        case _description = "description"
        case fieldConfigurationScheme
        case issueSecurityScheme
        case issueTypeScheme
        case issueTypeScreenScheme
        case key
        case lead
        case leadAccountId
        case name
        case notificationScheme
        case permissionScheme
        case projectTemplateKey
        case projectTypeKey
        case url
        case workflowScheme
    }

}
