//
// CreateNotificationSchemeDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of an notification scheme. */

public struct CreateNotificationSchemeDetails {




}
