//
// CustomFieldContextDefaultValueUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Default values to update. */

public struct CustomFieldContextDefaultValueUpdate {

    public var defaultValues: [CustomFieldContextDefaultValue]?

    public init(defaultValues: [CustomFieldContextDefaultValue]? = nil) {
        self.defaultValues = defaultValues
    }


}
