//
// CustomContextVariable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomContextVariable {

    /** Type of custom context variable. */
    public var type: String

    public init(type: String) {
        self.type = type
    }


}
