//
// CustomFieldContextProjectMapping.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a context to project association. */

public struct CustomFieldContextProjectMapping {

    /** The ID of the context. */
    public var contextId: String
    /** Whether context is global. */
    public var isGlobalContext: Bool?
    /** The ID of the project. */
    public var projectId: String?

    public init(contextId: String, isGlobalContext: Bool? = nil, projectId: String? = nil) {
        self.contextId = contextId
        self.isGlobalContext = isGlobalContext
        self.projectId = projectId
    }


}
