//
// DataClassificationTagBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The data classification. */

public struct DataClassificationTagBean {

    /** The color of the data classification object. */
    public var color: String?
    /** The description of the data classification object. */
    public var _description: String?
    /** The guideline of the data classification object. */
    public var guideline: String?
    /** The ID of the data classification object. */
    public var _id: String
    /** The name of the data classification object. */
    public var name: String?
    /** The rank of the data classification object. */
    public var rank: Int?
    /** The status of the data classification object. */
    public var status: String

    public init(color: String? = nil, _description: String? = nil, guideline: String? = nil, _id: String, name: String? = nil, rank: Int? = nil, status: String) {
        self.color = color
        self._description = _description
        self.guideline = guideline
        self._id = _id
        self.name = name
        self.rank = rank
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case color
        case _description = "description"
        case guideline
        case _id = "id"
        case name
        case rank
        case status
    }

}
