//
// DefaultWorkflow.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the default workflow. */

public struct DefaultWorkflow {

    /** Whether a draft workflow scheme is created or updated when updating an active workflow scheme. The draft is updated with the new default workflow. Defaults to &#x60;false&#x60;. */
    public var updateDraftIfNeeded: Bool?
    /** The name of the workflow to set as the default workflow. */
    public var workflow: String

    public init(updateDraftIfNeeded: Bool? = nil, workflow: String) {
        self.updateDraftIfNeeded = updateDraftIfNeeded
        self.workflow = workflow
    }


}
