//
// DefaultLevelValue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of scheme and new default level. */

public struct DefaultLevelValue {




}
