//
// EntityPropertyDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EntityPropertyDetails {

    /** The entity property ID. */
    public var entityId: Decimal
    /** The entity property key. */
    public var key: String
    /** The new value of the entity property. */
    public var value: String

    public init(entityId: Decimal, key: String, value: String) {
        self.entityId = entityId
        self.key = key
        self.value = value
    }


}
