//
// FieldConfigurationDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a field configuration. */

public struct FieldConfigurationDetails {

    /** The description of the field configuration. */
    public var _description: String?
    /** The name of the field configuration. Must be unique. */
    public var name: String

    public init(_description: String? = nil, name: String) {
        self._description = _description
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case name
    }

}
