//
// FieldConfigurationItemsDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of field configuration items. */

public struct FieldConfigurationItemsDetails {

    /** Details of fields in a field configuration. */
    public var fieldConfigurationItems: [FieldConfigurationItem]

    public init(fieldConfigurationItems: [FieldConfigurationItem]) {
        self.fieldConfigurationItems = fieldConfigurationItems
    }


}
