//
// FilterDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a filter. */

public struct FilterDetails {

    /** \\[Experimental\\] Approximate last used time. Returns the date and time when the filter was last used. Returns &#x60;null&#x60; if the filter hasn&#x27;t been used after tracking was enabled. For performance reasons, timestamps aren&#x27;t updated in real time and therefore may not be exactly accurate. */
    public var approximateLastUsed: Date?
    /** The description of the filter. */
    public var _description: String?
    /** The groups and projects that can edit the filter. This can be specified when updating a filter, but not when creating a filter. */
    public var editPermissions: [SharePermission]?
    /** Expand options that include additional filter details in the response. */
    public var expand: String?
    /** Whether the filter is selected as a favorite by any users, not including the filter owner. */
    public var favourite: Bool?
    /** The count of how many users have selected this filter as a favorite, including the filter owner. */
    public var favouritedCount: Int64?
    /** The unique identifier for the filter. */
    public var _id: String?
    /** The JQL query for the filter. For example, *project &#x3D; SSP AND issuetype &#x3D; Bug*. */
    public var jql: String?
    /** The name of the filter. */
    public var name: String
    /** The user who owns the filter. Defaults to the creator of the filter, however, Jira administrators can change the owner of a shared filter in the admin settings. */
    public var owner: AllOfFilterDetailsOwner?
    /** A URL to view the filter results in Jira, using the [Search for issues using JQL](#api-rest-api-2-filter-search-get) operation with the filter&#x27;s JQL string to return the filter results. For example, *https://your-domain.atlassian.net/rest/api/2/search?jql&#x3D;project+%3D+SSP+AND+issuetype+%3D+Bug*. */
    public var searchUrl: String?
    /** The URL of the filter. */
    public var _self: String?
    /** The groups and projects that the filter is shared with. This can be specified when updating a filter, but not when creating a filter. */
    public var sharePermissions: [SharePermission]?
    /** The users that are subscribed to the filter. */
    public var subscriptions: [FilterSubscription]?
    /** A URL to view the filter results in Jira, using the ID of the filter. For example, *https://your-domain.atlassian.net/issues/?filter&#x3D;10100*. */
    public var viewUrl: String?

    public init(approximateLastUsed: Date? = nil, _description: String? = nil, editPermissions: [SharePermission]? = nil, expand: String? = nil, favourite: Bool? = nil, favouritedCount: Int64? = nil, _id: String? = nil, jql: String? = nil, name: String, owner: AllOfFilterDetailsOwner? = nil, searchUrl: String? = nil, _self: String? = nil, sharePermissions: [SharePermission]? = nil, subscriptions: [FilterSubscription]? = nil, viewUrl: String? = nil) {
        self.approximateLastUsed = approximateLastUsed
        self._description = _description
        self.editPermissions = editPermissions
        self.expand = expand
        self.favourite = favourite
        self.favouritedCount = favouritedCount
        self._id = _id
        self.jql = jql
        self.name = name
        self.owner = owner
        self.searchUrl = searchUrl
        self._self = _self
        self.sharePermissions = sharePermissions
        self.subscriptions = subscriptions
        self.viewUrl = viewUrl
    }

}
