//
// GroupLabel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A group label. */

public struct GroupLabel {

    public enum ModelType: String, Codable { 
        case admin = "ADMIN"
        case single = "SINGLE"
        case multiple = "MULTIPLE"
    }
    /** The group label name. */
    public var text: String?
    /** The title of the group label. */
    public var title: String?
    /** The type of the group label. */
    public var type: ModelType?

    public init(text: String? = nil, title: String? = nil, type: ModelType? = nil) {
        self.text = text
        self.title = title
        self.type = type
    }


}
