//
// JexpIssues.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The JQL specifying the issues available in the evaluated Jira expression under the &#x60;issues&#x60; context variable. */

public struct JexpIssues {

    /** The JQL query that specifies the set of issues available in the Jira expression. */
    public var jql: AllOfJexpIssuesJql?

    public init(jql: AllOfJexpIssuesJql? = nil) {
        self.jql = jql
    }


}
