//
// JiraWorkflowStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a status. */

public struct JiraWorkflowStatus {

    public enum StatusCategory: String, Codable { 
        case todo = "TODO"
        case inProgress = "IN_PROGRESS"
        case done = "DONE"
    }
    /** The description of the status. */
    public var _description: String?
    /** The ID of the status. */
    public var _id: String?
    /** The name of the status. */
    public var name: String?
    public var scope: WorkflowScope?
    /** The category of the status. */
    public var statusCategory: StatusCategory?
    /** The reference of the status. */
    public var statusReference: String?
    /** The &#x60;statuses.usages&#x60; expand is an optional parameter that can be used when reading and updating statuses in Jira. It provides additional information about the projects and issue types associated with the requested statuses. */
    public var usages: [ProjectIssueTypes]?

    public init(_description: String? = nil, _id: String? = nil, name: String? = nil, scope: WorkflowScope? = nil, statusCategory: StatusCategory? = nil, statusReference: String? = nil, usages: [ProjectIssueTypes]? = nil) {
        self._description = _description
        self._id = _id
        self.name = name
        self.scope = scope
        self.statusCategory = statusCategory
        self.statusReference = statusReference
        self.usages = usages
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case _id = "id"
        case name
        case scope
        case statusCategory
        case statusReference
        case usages
    }

}
