//
// JiraExpressionsAnalysis.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the analysed Jira expression. */

public struct JiraExpressionsAnalysis {

    /** The results of Jira expressions analysis. */
    public var results: [JiraExpressionAnalysis]

    public init(results: [JiraExpressionAnalysis]) {
        self.results = results
    }


}
