//
// JiraExpressionEvalRequestBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JiraExpressionEvalRequestBean {

    /** The context in which the Jira expression is evaluated. */
    public var context: AllOfJiraExpressionEvalRequestBeanContext?
    /** The Jira expression to evaluate. */
    public var expression: String

    public init(context: AllOfJiraExpressionEvalRequestBeanContext? = nil, expression: String) {
        self.context = context
        self.expression = expression
    }


}
