//
// JqlQueryUnitaryOperand.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An operand that can be part of a list operand. */

public struct JqlQueryUnitaryOperand {




}
