//
// ListOperand.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An operand that is a list of values. */

public struct ListOperand {

    /** Encoded operand, which can be used directly in a JQL query. */
    public var encodedOperand: String?
    /** The list of operand values. */
    public var values: [JqlQueryUnitaryOperand]

    public init(encodedOperand: String? = nil, values: [JqlQueryUnitaryOperand]) {
        self.encodedOperand = encodedOperand
        self.values = values
    }


}
