//
// NotificationRecipients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the users and groups to receive the notification. */

public struct NotificationRecipients {




}
