//
// OrderOfIssueTypes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An ordered list of issue type IDs and information about where to move them. */

public struct OrderOfIssueTypes {

    public enum Position: String, Codable { 
        case first = "First"
        case last = "Last"
    }
    /** The ID of the issue type to place the moved issue types after. Required if &#x60;position&#x60; isn&#x27;t provided. */
    public var after: String?
    /** A list of the issue type IDs to move. The order of the issue type IDs in the list is the order they are given after the move. */
    public var issueTypeIds: [String]
    /** The position the issue types should be moved to. Required if &#x60;after&#x60; isn&#x27;t provided. */
    public var position: Position?

    public init(after: String? = nil, issueTypeIds: [String], position: Position? = nil) {
        self.after = after
        self.issueTypeIds = issueTypeIds
        self.position = position
    }


}
