//
// ParsedJqlQueries.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of parsed JQL queries. */

public struct ParsedJqlQueries {

    /** A list of parsed JQL queries. */
    public var queries: [ParsedJqlQuery]

    public init(queries: [ParsedJqlQuery]) {
        self.queries = queries
    }


}
