//
// PermissionsKeysBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PermissionsKeysBean {

    /** A list of permission keys. */
    public var permissions: [String]

    public init(permissions: [String]) {
        self.permissions = permissions
    }


}
