//
// PermissionGrant.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about a permission granted to a user or group. */

public struct PermissionGrant {




}
