//
// PermissionScheme.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a permission scheme. */

public struct PermissionScheme {




}
