//
// PropertyKeys.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List of property keys. */

public struct PropertyKeys {

    /** Property key details. */
    public var keys: [PropertyKey]?

    public init(keys: [PropertyKey]? = nil) {
        self.keys = keys
    }


}
