//
// PublishDraftWorkflowScheme.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the status mappings for publishing a draft workflow scheme. */

public struct PublishDraftWorkflowScheme {

    /** Mappings of statuses to new statuses for issue types. */
    public var statusMappings: [StatusMapping]?

    public init(statusMappings: [StatusMapping]? = nil) {
        self.statusMappings = statusMappings
    }


}
