//
// RegisteredWebhook.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** ID of a registered webhook or error messages explaining why a webhook wasn&#x27;t registered. */

public struct RegisteredWebhook {

    /** The ID of the webhook. Returned if the webhook is created. */
    public var createdWebhookId: Int64?
    /** Error messages specifying why the webhook creation failed. */
    public var errors: [String]?

    public init(createdWebhookId: Int64? = nil, errors: [String]? = nil) {
        self.createdWebhookId = createdWebhookId
        self.errors = errors
    }


}
