//
// SanitizedJqlQueries.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The sanitized JQL queries for the given account IDs. */

public struct SanitizedJqlQueries {

    /** The list of sanitized JQL queries. */
    public var queries: [SanitizedJqlQuery]?

    public init(queries: [SanitizedJqlQuery]? = nil) {
        self.queries = queries
    }


}
