//
// ScreenableField.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A screen tab field. */

public struct ScreenableField {

    /** The ID of the screen tab field. */
    public var _id: String?
    /** The name of the screen tab field. Required on create and update. The maximum length is 255 characters. */
    public var name: String?

    public init(_id: String? = nil, name: String? = nil) {
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
    }

}
