//
// SearchAutoCompleteFilter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of how to filter and list search auto complete information. */

public struct SearchAutoCompleteFilter {

    /** Include collapsed fields for fields that have non-unique names. */
    public var includeCollapsedFields: Bool?
    /** List of project IDs used to filter the visible field details returned. */
    public var projectIds: [Int64]?

    public init(includeCollapsedFields: Bool? = nil, projectIds: [Int64]? = nil) {
        self.includeCollapsedFields = includeCollapsedFields
        self.projectIds = projectIds
    }


}
