//
// SecuritySchemes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List of security schemes. */

public struct SecuritySchemes {

    /** List of security schemes. */
    public var issueSecuritySchemes: [SecurityScheme]?

    public init(issueSecuritySchemes: [SecurityScheme]? = nil) {
        self.issueSecuritySchemes = issueSecuritySchemes
    }


}
