//
// SecuritySchemeLevelBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SecuritySchemeLevelBean {

    /** The description of the issue security scheme level. */
    public var _description: String?
    /** Specifies whether the level is the default level. False by default. */
    public var isDefault: Bool?
    /** The list of level members which should be added to the issue security scheme level. */
    public var members: [SecuritySchemeLevelMemberBean]?
    /** The name of the issue security scheme level. Must be unique. */
    public var name: String

    public init(_description: String? = nil, isDefault: Bool? = nil, members: [SecuritySchemeLevelMemberBean]? = nil, name: String) {
        self._description = _description
        self.isDefault = isDefault
        self.members = members
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case isDefault
        case members
        case name
    }

}
