//
// ServiceRegistry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ServiceRegistry {

    /** service description */
    public var _description: String?
    /** service ID */
    public var _id: UUID?
    /** service name */
    public var name: String?
    /** organization ID */
    public var organizationId: String?
    /** service revision */
    public var revision: String?
    public var serviceTier: ServiceRegistryTier?

    public init(_description: String? = nil, _id: UUID? = nil, name: String? = nil, organizationId: String? = nil, revision: String? = nil, serviceTier: ServiceRegistryTier? = nil) {
        self._description = _description
        self._id = _id
        self.name = name
        self.organizationId = organizationId
        self.revision = revision
        self.serviceTier = serviceTier
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case _id = "id"
        case name
        case organizationId
        case revision
        case serviceTier
    }

}
