//
// SetDefaultLevelsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of new default levels. */

public struct SetDefaultLevelsRequest {




}
