//
// TimeTrackingProvider.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details about the time tracking provider. */

public struct TimeTrackingProvider {

    /** The key for the time tracking provider. For example, *JIRA*. */
    public var key: String
    /** The name of the time tracking provider. For example, *JIRA provided time tracking*. */
    public var name: String?
    /** The URL of the configuration page for the time tracking provider app. For example, *_/example/config/url*. This property is only returned if the &#x60;adminPageKey&#x60; property is set in the module descriptor of the time tracking provider app. */
    public var url: String?

    public init(key: String, name: String? = nil, url: String? = nil) {
        self.key = key
        self.name = name
        self.url = url
    }


}
