//
// Watchers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The details of watchers on an issue. */

public struct Watchers {

    /** Whether the calling user is watching this issue. */
    public var isWatching: Bool?
    /** The URL of these issue watcher details. */
    public var _self: String?
    /** The number of users watching this issue. */
    public var watchCount: Int?
    /** Details of the users watching this issue. */
    public var watchers: [User]?

    public init(isWatching: Bool? = nil, _self: String? = nil, watchCount: Int? = nil, watchers: [User]? = nil) {
        self.isWatching = isWatching
        self._self = _self
        self.watchCount = watchCount
        self.watchers = watchers
    }

    public enum CodingKeys: String, CodingKey { 
        case isWatching
        case _self = "self"
        case watchCount
        case watchers
    }

}
