//
// WebhookRegistrationDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of webhooks to register. */

public struct WebhookRegistrationDetails {

    /** The URL that specifies where to send the webhooks. This URL must use the same base URL as the Connect app. Only a single URL per app is allowed to be registered. */
    public var url: String
    /** A list of webhooks. */
    public var webhooks: [WebhookDetails]

    public init(url: String, webhooks: [WebhookDetails]) {
        self.url = url
        self.webhooks = webhooks
    }


}
