//
// WorklogIdsRequestBean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WorklogIdsRequestBean {

    /** A list of worklog IDs. */
    public var ids: [Int64]

    public init(ids: [Int64]) {
        self.ids = ids
    }


}
