//
// IssueTypeIdsToRemove.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of issue type IDs to be removed from the field configuration scheme. */

public struct IssueTypeIdsToRemove {

    /** The list of issue type IDs. Must contain unique values not longer than 255 characters and not be empty. Maximum of 100 IDs. */
    public var issueTypeIds: [String]

    public init(issueTypeIds: [String]) {
        self.issueTypeIds = issueTypeIds
    }


}
