//
// WorkflowAssociationStatusMapping.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of status mappings. */

public struct WorkflowAssociationStatusMapping {

    /** The ID of the status in the new workflow. */
    public var newStatusId: String
    /** The ID of the status in the old workflow that isn&#x27;t present in the new workflow. */
    public var oldStatusId: String

    public init(newStatusId: String, oldStatusId: String) {
        self.newStatusId = newStatusId
        self.oldStatusId = oldStatusId
    }


}
