//
// WorkflowRulesSearch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the workflow and its transition rules. */

public struct WorkflowRulesSearch {

    /** Use expand to include additional information in the response. This parameter accepts &#x60;transition&#x60; which, for each rule, returns information about the transition the rule is assigned to. */
    public var expand: String?
    /** The list of workflow rule IDs. */
    public var ruleIds: [UUID]
    /** The workflow ID. */
    public var workflowEntityId: UUID

    public init(expand: String? = nil, ruleIds: [UUID], workflowEntityId: UUID) {
        self.expand = expand
        self.ruleIds = ruleIds
        self.workflowEntityId = workflowEntityId
    }


}
