//
// WorkflowSchemeReadRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The workflow scheme read request body. */

public struct WorkflowSchemeReadRequest {

    /** The list of project IDs to query. */
    public var projectIds: [String]?
    /** The list of workflow scheme IDs to query. */
    public var workflowSchemeIds: [String]?

    public init(projectIds: [String]? = nil, workflowSchemeIds: [String]? = nil) {
        self.projectIds = projectIds
        self.workflowSchemeIds = workflowSchemeIds
    }


}
