//
// ProjectLandingPageInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProjectLandingPageInfo {

    public var attributes: [String:String]?
    public var boardId: Int64?
    public var boardName: String?
    public var projectKey: String?
    public var projectType: String?
    public var queueCategory: String?
    public var queueId: Int64?
    public var queueName: String?
    public var simpleBoard: Bool?
    public var simplified: Bool?
    public var url: String?

    public init(attributes: [String:String]? = nil, boardId: Int64? = nil, boardName: String? = nil, projectKey: String? = nil, projectType: String? = nil, queueCategory: String? = nil, queueId: Int64? = nil, queueName: String? = nil, simpleBoard: Bool? = nil, simplified: Bool? = nil, url: String? = nil) {
        self.attributes = attributes
        self.boardId = boardId
        self.boardName = boardName
        self.projectKey = projectKey
        self.projectType = projectType
        self.queueCategory = queueCategory
        self.queueId = queueId
        self.queueName = queueName
        self.simpleBoard = simpleBoard
        self.simplified = simplified
        self.url = url
    }


}
