//
// ProjectFeature.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of a project feature. */

public struct ProjectFeature {

    public enum State: String, Codable { 
        case enabled = "ENABLED"
        case disabled = "DISABLED"
        case comingSoon = "COMING_SOON"
    }
    /** The key of the feature. */
    public var feature: String?
    /** URI for the image representing the feature. */
    public var imageUri: String?
    /** Localized display description for the feature. */
    public var localisedDescription: String?
    /** Localized display name for the feature. */
    public var localisedName: String?
    /** List of keys of the features required to enable the feature. */
    public var prerequisites: [String]?
    /** The ID of the project. */
    public var projectId: Int64?
    /** The state of the feature. When updating the state of a feature, only ENABLED and DISABLED are supported. Responses can contain all values */
    public var state: State?
    /** Whether the state of the feature can be updated. */
    public var toggleLocked: Bool?

    public init(feature: String? = nil, imageUri: String? = nil, localisedDescription: String? = nil, localisedName: String? = nil, prerequisites: [String]? = nil, projectId: Int64? = nil, state: State? = nil, toggleLocked: Bool? = nil) {
        self.feature = feature
        self.imageUri = imageUri
        self.localisedDescription = localisedDescription
        self.localisedName = localisedName
        self.prerequisites = prerequisites
        self.projectId = projectId
        self.state = state
        self.toggleLocked = toggleLocked
    }


}
