//
// ProjectIssueTypeMappings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The project and issue type mappings. */

public struct ProjectIssueTypeMappings {

    /** The project and issue type mappings. */
    public var mappings: [ProjectIssueTypeMapping]

    public init(mappings: [ProjectIssueTypeMapping]) {
        self.mappings = mappings
    }


}
