//
// ProjectCategory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A project category. */

public struct ProjectCategory {

    /** The description of the project category. */
    public let description: String?
    /** The ID of the project category. */
    public let id: String?
    /** The name of the project category. Required on create, optional on update. */
    public let name: String?
    /** The URL of the project category. */
    public let _self: String?

    public init(description: String? = nil, id: String? = nil, name: String? = nil, _self: String? = nil) {
        self.description = description
        self.id = id
        self.name = name
        self._self = _self
    }
    
    internal init(client: Components.Schemas.ProjectCategory?) {
        self.description = client?.description
        self.id = client?.id
        self.name = client?.name
        self._self = client?._self
    }

}
