//
// Votes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The details of votes on an issue. */

public struct Votes {

    /** Whether the user making this request has voted on the issue. */
    public var hasVoted: Bool?
    /** The URL of these issue vote details. */
    public var _self: String?
    /** List of the users who have voted on this issue. An empty list is returned when the calling user doesn&#x27;t have the *View voters and watchers* project permission. */
    public var voters: [User]?
    /** The number of votes on the issue. */
    public var votes: Int64?

    public init(hasVoted: Bool? = nil, _self: String? = nil, voters: [User]? = nil, votes: Int64? = nil) {
        self.hasVoted = hasVoted
        self._self = _self
        self.voters = voters
        self.votes = votes
    }
    
    internal init(client: Components.Schemas.Votes?) {
        self.hasVoted = client?.hasVoted
        self._self = client?._self
        self.voters = client?.voters?.map{ User(client: $0) }
        self.votes = client?.votes
    }
}
