//
// StatusMappingDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The mapping of old to new status ID for a specific project and issue type. */

public struct StatusMappingDTO {




}
