//
// VersionApprover.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains details about a version approver. */

public struct VersionApprover {
    let accountId: String?
    let declineReason: String?
    let description: String?
    let status: String?
    
    internal init(client: Components.Schemas.VersionApprover?) {
        self.accountId = client?.accountId
        self.description = client?.description
        self.declineReason = client?.declineReason
        self.status = client?.status
    }
}
