//
// ApplicationProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of an application property. */

public struct ApplicationProperty {

    /** The allowed values, if applicable. */
    public let allowedValues: [String]?
    /** The default value of the application property. */
    public let defaultValue: String?
    /** The description of the application property. */
    public let desc: String?
    public let example: String?
    /** The ID of the application property. The ID and key are the same. */
    public let id: String?
    /** The key of the application property. The ID and key are the same. */
    public let key: String?
    /** The name of the application property. */
    public let name: String?
    /** The data type of the application property. */
    public let type: String?
    /** The new value. */
    public let value: String?

    public init(allowedValues: [String]? = nil, defaultValue: String? = nil, desc: String? = nil, example: String? = nil, id: String? = nil, key: String? = nil, name: String? = nil, type: String? = nil, value: String? = nil) {
        self.allowedValues = allowedValues
        self.defaultValue = defaultValue
        self.desc = desc
        self.example = example
        self.id = id
        self.key = key
        self.name = name
        self.type = type
        self.value = value
    }
    
    internal init(client: Components.Schemas.ApplicationProperty?) {
        self.allowedValues = client?.allowedValues
        self.defaultValue = client?.defaultValue
        self.desc = client?.desc
        self.example = client?.example
        self.id = client?.id
        self.key = client?.key
        self.name = client?.name
        self.type = client?._type
        self.value = client?.value
    }
}
